### ISSUE TITLE
如何实现集合元素抽取？类似jsonpath 语法

### ISSUE THREAD

**Issue by zhoupj** [killme2008/aviator#105]
比如，我写 array[*].amount 表示抽取数组array下面每个元素中的amount属性，返回集合

**Comment by killme2008** [comment]
这种需求可以自己写 lambda

```
reduce(array, lambda (result, x) ->  list.add(result, x.amount) end, list.new()) 
```

其中 `list.add` 和 `list.new` 是需要你自己实现的自定义函数，表示往一个 list 添加元素，以及 new 一个新 list

**Comment by killme2008** [comment]
4.1.2 版本计划提供下这类函数  `seq.add` ， `seq.remove` 以及 `seq.list`, `seq.set` 等。
