### ISSUE TITLE
如何获取表达式中变量与变量对应实际值的集合呢？

### ISSUE THREAD

**Issue by jiawenjun1126** [killme2008/aviator#108]
如何获取表达式中变量与实际变量对应值的集合呢？

**Comment by killme2008** [comment]
请详细说明问题。

**Comment by killme2008** [comment]
如果你是要在表达式内获取 env 环境，可以通过特殊变量 `__env__` 获取。

**Comment by killme2008** [comment]
随时可以打印，比如 `a=2 ; println(__env__);"

**Comment by jiawenjun1126** [comment]
表述的不太清楚，我举个例子，
public class Persion{
private int age;
get&set..
}
Person person = new Person();
person.setAge(100);
Map<String,Object> map = new HashMap();
map.put("foo",person)

expression.execute("foo.age>10",map);

类似与上述嵌套Bean情况，是否能提供方法进行返回变量与值的映射Map。
1.目前看到工具类里面 已有Expression.getVariableFullNames()方法返回变量的列表，能将变量参数对应的实际值一并返回呢。例如返回 foo.age = 100这样的集合。

我理解的调用expression.execute()应该也进行获取变量值了。当然也可以自行获取传入Env里面的值，但是这样会导致获取两次，1.业务代码获取一次，2.表达式执行是获取一次。着实没有必要。表达式引擎获取是必须的，所以如果能提供接口返回，更好了。
因为刚刚接入在调研此框架，有表述不对的地方，请指正。谢谢。

**Comment by killme2008** [comment]
@jiawenjun1126 那就是 `__env__`　变量的用途。

**Comment by jiawenjun1126** [comment]
> 随时可以打印，比如 `a=2 ; println(__env__)`



> @jiawenjun1126 那就是 `__env__`　变量的用途。

这个特殊变量，如何获取呢？

**Comment by killme2008** [comment]
直接在表达式里写上就可以使用的，要返回就放到最后了。

**Comment by killme2008** [comment]
@jiawenjun1126 这个暂时没有写到文档，后面补充下。

**Comment by killme2008** [comment]
已在 4.0 文档做了说明

https://github.com/killme2008/aviator/wiki/4.0-%E5%8A%9F%E8%83%BD%E8%AF%A6%E7%BB%86%E8%A7%A3%E6%9E%90
