### ISSUE TITLE
如何获取所有变量

### ISSUE THREAD

**Issue by zhoupj** [killme2008/aviator#109]
表达式： map(pay,lambda(x)->long(x.id) end)
数据：{"pay":{"id",“12”,"name":"xxxx"}}
通过  AviatorEvaluator.compile() 获取的变量，只有pay ，没有 pay.id  请教下如何 解决呢？

**Comment by killme2008** [comment]
这个不是直接 pay.id 就可以获取了？为什么还要 map ?你这里并不是一个 sequence 序列，而是一个 map。

**Comment by killme2008** [comment]
哦，你是要获取变量名称 pay.id，这个做不到的，编译只知道 pay，并不知道运行时你会获取一个 pay.id，那是运行时的临时变量。
