### ISSUE TITLE
Hi, 能补充一下变量的命名文档吗？

### ISSUE THREAD

**Issue by mylxy** [killme2008/aviator#11]
我发现，变量的命名，可以包含数字，下划线，中英文等，甚至少量的物殊符号，比如包含$这个变量名称是支持的，但是包含#的变量名称是不支持的，但是我知道我列举的肯定是不全的，所以我很需要一份文档来参考，希望作者考虑下，能不能加下这个文档说明，谢谢。

**Comment by killme2008** [comment]
就是 Java 变量的命名规则

https://docs.oracle.com/cd/E19798-01/821-1841/bnbuk/index.html

**Comment by mylxy** [comment]
thanks
