### ISSUE TITLE
表达式复杂时，计算结果为NAN

### ISSUE THREAD

**Issue by zhangzhenhua92** [killme2008/aviator#113]
`    public void testAviator(){
        Map<String , Object> param = new HashMap<String , Object>();
        param.put("a",90000.0);
        param.put("b",55.0);
        param.put("c",1);
        param.put("d",1);
        param.put("e",3);
        String express = "(a-b)*(c/12*d)/(math.pow((1+c/12*d),e)-1)+(a-b)*(c/12*d)";
        try{
            Expression expression  = AviatorEvaluator.compile(express);
            Double result = (Double)expression.execute(param);
        }catch (Exception e){
            System.out.print(e);
        }
    }
}`

如上述代码，我把c替换为12的整数倍，就没有问题，否则，结果就是NaN.
请问下大神，这个是bug还是我需要其他配置呢？

**Comment by zhangzhenhua92** [comment]
public void testAviator(){
        Map<String , Object> param = new HashMap<String , Object>();
        param.put("a",90000.0);
        param.put("b",55.0);
        param.put("c",1);
        param.put("d",1);
        param.put("e",3);
        String express = "(a-b)*(c/12*d)/(math.pow((1+c/12*d),e)-1)+(a-b)*(c/12*d)";
        try{
            Expression expression  = AviatorEvaluator.compile(express);
            Double result = (Double)expression.execute(param);
        }catch (Exception e){
            System.out.print(e);
        }
    }
}

**Comment by zhangzhenhua92** [comment]
这是个金融公式，我用a，b，c，d，e做了简化。

**Comment by killme2008** [comment]
你好， aviator 支持运行时跟踪，你可以打开 TRACE_EVAL 选项：

```java

  public static void testAviator() {
    Map<String , Object> param = new HashMap<String , Object>();
    param.put("a",90000.0);
    param.put("b",55.0);
    param.put("c",1);
    param.put("d",1);
    param.put("e",3);
    String express = "(a-b)*(c/12*d)/(math.pow((1+c/12*d),e)-1)+(a-b)*(c/12*d)";
    try{
      AviatorEvaluator.setOption(Options.TRACE_EVAL, true);
      Expression expression  = AviatorEvaluator.compile(express);
      Double result = (Double)expression.execute(param);
      System.out.println(result);
    }catch (Exception e){
      System.out.print(e);
    }
  }
```
输出

```
[Aviator TRACE]          <JavaType, 90000.0, Double> -sub <JavaType, 55.0, Double> => <Double, 89945.0>
[Aviator TRACE]          <JavaType, 1, Integer> / <Long, 12> => <Long, 0>
[Aviator TRACE]          <Long, 0> * <JavaType, 1, Integer> => <Long, 0>
[Aviator TRACE]          <Double, 89945.0> * <Long, 0> => <Double, 0.0>
[Aviator TRACE]          <JavaType, 1, Integer> / <Long, 12> => <Long, 0>
[Aviator TRACE]          <Long, 0> * <JavaType, 1, Integer> => <Long, 0>
[Aviator TRACE]          <Long, 1> + <Long, 0> => <Long, 1>
[Aviator TRACE] Func   : math.pow(<Long, 1>,<JavaType, 3, Integer>)
[Aviator TRACE]          <Double, 1.0> -sub <Long, 1> => <Double, 0.0>
[Aviator TRACE]          <Double, 0.0> / <Double, 0.0> => <Double, NaN>
[Aviator TRACE]          <JavaType, 90000.0, Double> -sub <JavaType, 55.0, Double> => <Double, 89945.0>
[Aviator TRACE]          <JavaType, 1, Integer> / <Long, 12> => <Long, 0>
[Aviator TRACE]          <Long, 0> * <JavaType, 1, Integer> => <Long, 0>
[Aviator TRACE]          <Double, 89945.0> * <Long, 0> => <Double, 0.0>
[Aviator TRACE]          <Double, NaN> + <Double, 0.0> => <Double, NaN>
[Aviator TRACE] Result : NaN
NaN

```

可以看到关键环节是出现了 ` <Double, 0.0> / <Double, 0.0> => <Double, NaN>`，也就是 `0.0/0.0`，导致结果为 NAN，问题就是由于 `(math.pow((1+c/12*d),e)-1)` 结果为 0。

也就是 `math.pow((1+1/12*1), 1)` 的结果为 1，我猜测你可能是需要将 c 设置为 double 类型，否则 1/12 按照整形运算结果为 0。

```java
  param.put("c", 1.0);
```
结果为
```
35111.79193319121
```

TRACE_EVAL 很强大，推荐在遇到的问题，先自行分析。

**Comment by killme2008** [comment]
另外涉及金融计算的话，推荐使用高精度计算，可以打开 `ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL`，以及使用大数运算，参见 

https://github.com/killme2008/aviator/wiki#%E5%A4%A7%E6%95%B0%E8%AE%A1%E7%AE%97%E5%92%8C%E7%B2%BE%E5%BA%A6

**Comment by killme2008** [comment]
没有更多问题我关闭了。

**Comment by zhangzhenhua92** [comment]
多谢大神！
