### ISSUE TITLE
字符串小于号比较，env不包含对应daystring的key时，为什么返回true

### ISSUE THREAD

**Issue by volzengwen** [killme2008/aviator#114]
如expression:daystring<'20190313'||string.contains('rmrk','alipay')
   env:   map("rmrk"->"tencent")

exp.execute(env)   return true

如果需要当env不包含daystring的时候， daystring<'20190313' 返回 false 。是否能支持

**Comment by killme2008** [comment]
抱歉，这个是 aviator 的规则，也就是 null （或者 nil) 对象比任何对象都小。

你可以将表达式修改为
```
(daystring !=nil ? daystring<'20190313': false) || string.contains('rmrk','alipay')
```

**Comment by volzengwen** [comment]
> 抱歉，这个是 aviator 的规则，也就是 null （或者 nil) 对象比任何对象都小，除了等于他本身。
> 
> 你可以将表达式修改为
> 
> ```
> (daystring !=nil ? daystring<'20190313': false) || string.contains('rmrk','alipay')
> ```

非常感谢你的答复。找到了关于字符串比较规则时，调用AviatorString下的conpare方法判断，如果JavaType类型且对象不在的时候，返回0或1
 

另外想请教个问题，因为由web端维护较复杂规则，暂时没法加类型判断是否位空。
我在OperatorType下的eval方法，在LT,LE,GT,GE的时候，加入了是否为空的判断可以解决。发现一个很奇怪的情况：
OperatorType.eval方法加入代码：
 case LT:
    	  if("JavaType".equals(args[0].getAviatorType().name())){
          	if (args[0].getValue(env) == null) {
                  return AviatorBoolean.valueOf(false);
                }
          };
        result = args[0].compare(args[1], env);
        return AviatorBoolean.valueOf(result < 0);

执行代码：
Expression exp=  AviatorEvaluator.compile("txnamt < '1' ");
	Map<String, Object> env=new HashMap<String, Object>();
	System.out.println((Boolean) exp.execute(env));
结果为false
如果加上跟踪参数，
AviatorEvaluator.setOption(Options.TRACE_EVAL, true);
结果为true

----------------------问题------------------------------------
AviatorEvaluator.setOption(Options.TRACE_EVAL, true);
没调试出这个参数是如何影响代码是否调用到OperType的eval方法。
当前我用3.3的版本，和4.0的版本都会有这样的问题

盼回复

**Comment by killme2008** [comment]
@volzengwen 因为只有在 `TRACE_EVAL` 模式，或者自定义了运算符的情况下，才会去执行 `OperatorType.eval` 方法。其他情况下是不会的，直接编译成字节码执行了，不会加入这种 hook 调用。

**Comment by killme2008** [comment]
你这种情况还有一种解决办法是对 env 做预处理，对于表达式中不存在的变量做填充，表达式的变量可以通过 `expression.getVarNames()` 获得。

**Comment by volzengwen** [comment]
感谢回复。
i think it will kill me at 2019😄

接编译成字节码的话，
这个expression的编译，理论上是否能在本地对编译的类加入相应的动作呢？

哪怕像string.contains("rmrk","aaa")的规则解析一样，env不包含rmrk element时。向上抛出NullPointException

**Comment by killme2008** [comment]
@volzengwen 非常不推荐在生产环境开启 trace_eval，这个非常影响性能的。

本质上来说你这里是希望nil 是最大的，而不是最小的，对吧？也许可以加入选项来倒转这个规则。

**Comment by volzengwen** [comment]
感谢回复

完整的说，我希望在大于，小于，等于的判断里面，如果env不存在变量，那么返回false。这样子对于规则1||规则2||规则3的情形，如果一直false，就能执行到规则3了。

因为场景的需要是:
不存在即false，只要存在存在其1并匹配通过，就命中

**Comment by killme2008** [comment]
这种的需求还是推荐你修改表达式了，这才是最佳的解决办法。你可以做个预处理，取出所有的变量名，跑，拼接成类似

`a != nil && b!=ni && c!=nil ` 这样的表达式，然后跟真正的表达式结合拼接

` a != nil && b!=ni && c!=nil && (实际的表达式)`

**Comment by volzengwen** [comment]
感谢回复

嗯，如果像上面加!=nil的话，在expression.getVarNames() 时就可以拦截处理了。

然后，由于对hook调用理解不多，我想，能不能自行修改源码，把类似我在OperType加入的判断动作，加入编译exp字节码里面。我在对这部分打一个定制版的aviator.jar😄

这个想法突兀了哈，见谅

**Comment by killme2008** [comment]
@volzengwen 这个想法是可以的，但是后续我这边的升级，分支版本一般就很难再跟着升级了，需要你们自己维护了，通常是不建议的。

这个 issue 我先关闭了，如果你有更好的建议，欢迎提出。

**Comment by volzengwen** [comment]
可惜现在处于过渡阶段，我们没那么快可以对前端的规则管理做改动。 月底就要先在后台兼容这个比较的需求了。 把类似我在OperType加入的判断动作，加入编译exp字节码里面，能提供个思路吗？ 

 目前看到this.mv那部分，没看明白，AviatorJavaType的compare方法是在哪里开始被调用的。  不像eval的时候，在operatorType就可以看到怎么处理compare方法 返回的结果。
