### ISSUE TITLE
表达式合法性校验

### ISSUE THREAD

**Issue by fightress** [killme2008/aviator#117]
如何判断一个表达式是否使用了不支持的函数？预判断表达式是否可以正确编译、依赖env可以正确计算？

**Comment by killme2008** [comment]
不支持静态检查，只能通过运行时 catch  FunctionNotFoundException 来确认。

http://fnil.net/aviator/apidocs/com/googlecode/aviator/exception/FunctionNotFoundException.html

**Comment by fightress** [comment]
好吧 谢谢~
不知道后续会不会考虑增加静态检查功能，对于预录入的表达式能直接报告问题

**Comment by killme2008** [comment]
主要 aviator 的类型都是动态，没有执行的话是不知道类型，除非后续实现类型绑定，就可以在编译期做检查了。
