### ISSUE TITLE
4.1.1版本中AviatorLong类构造器问题

### ISSUE THREAD

**Issue by mo8396use** [killme2008/aviator#118]
4.1.1版本中AviatorLong类构造器貌似不是public 修饰的，导致在项目中使用出现AviatorLong(java.lang.Number) is not public in com.googlecode.aviator.runtime.type.AviatorLong; cannot be accessed from outside package，请看一下，谢谢！

**Comment by killme2008** [comment]
请统一使用 `AvatorLong.valueOf(x)` 方法替代，抱歉。这个改动忘了在 changelog 里加上。
