### ISSUE TITLE
针对表达式“1/2”，能不能强制使用浮点数运算，从而得到结果0.5，而不是0

### ISSUE THREAD

**Issue by haoyuanqiang** [killme2008/aviator#121]
表达式内容是不确定的，所以没办法要求表达式内容必须写成“1.0/2”，请问有没有方法实现我的需求？
PS：我看过文档了，但是没有找到有效的方法

**Comment by killme2008** [comment]
你可以重载所有的算术运算符，强制为操作数加上 double 转换，参见 

https://github.com/killme2008/aviator/wiki#%E9%87%8D%E8%BD%BD%E8%BF%90%E7%AE%97%E7%AC%A6

**Comment by killme2008** [comment]
可以关注下 https://github.com/killme2008/aviator/issues/124
