### ISSUE TITLE
关于ENV重载了containsKey和增加seq.contains_key函数

### ISSUE THREAD

**Issue by linlay** [killme2008/aviator#122]
项目中需要判断环境env中是否有某个键，但目前key:null等同于null，
并查看源码后发现ENV实现了map接口，重载了containsKey

项目场景为数据库update，json是入参，sql语句会自动拼接，所以
{field:null} 和 {} 是2个概念，前者表示将field UPDATE成null，后者表示不对该field做任何操作。

另外希望增加seq.contains_key函数，原理同上。

**Comment by killme2008** [comment]
已在 4.2.0 修复，增加了 `seq.contains_key` 函数

https://github.com/killme2008/aviator/releases/tag/aviator-4.2.0

**Comment by zengxiaowengit** [comment]
awesome feature.  :)   👍
