### ISSUE TITLE
自定义函数中如何获取参数？ 不是计算结果

### ISSUE THREAD

**Issue by icevb6** [killme2008/aviator#128]
自定义函数中如何获取参数？ 不是计算结果

**Comment by killme2008** [comment]
什么意思？ 自定义函数里的 call 系列方法的参数就是你的函数参数，还需要怎么获取？

**Comment by icevb6** [comment]
举个例子，如函数：BLANK(a,b)

我想在继承 的 AbstractFunction 中获取 a 这个参数的名字，而不是 a 的值 。
也就是 a 先不计算，我需要根据b参数的值来决定 a 的取值
public AviatorObject call(Map<String, Object> env, AviatorObject arg1, AviatorObject arg2) {
  if(arg2.getValue(env) == '2016-12-31'){
	Object val = getDataFromDB(a,'2016-12-31');
         return val;
 }else if(arg2.getValue(env) == '2017-12-31'){
       Object val = getDataFromDB(a,'2017-12-31');
        return val;
}
    return arg1.getValue(env);
}
代码不一定对，就是举个例子。

**Comment by icevb6** [comment]
@killme2008 ,大周末，又是假期，回复还很及时，非常感谢！

**Comment by icevb6** [comment]
最好增加一个上下文的概念

**Comment by killme2008** [comment]
你要的是类似宏这样的东西了，暂时还无法支持。

**Comment by icevb6** [comment]
有计划支持吗？

**Comment by killme2008** [comment]
理论上说，我可以给到请求的 context的，比如这个函数调用有什么参数，参数名称之类，但是无法做到这些参数不先被求值。宏暂时没有打算支持。

**Comment by icevb6** [comment]
这样也可以，先被求值也行，context那个怎么获取？

**Comment by killme2008** [comment]
可以实现，暂未实现。

**Comment by icevb6** [comment]
我想用你的这个引擎，你可以告诉我实现的方法吗？我自己先临时对付一下，然后等你发布新版本。

**Comment by killme2008** [comment]
@icevb6 没有那么容易搞，需要在编译过程中将收集到的信息保存到运行时。

**Comment by killme2008** [comment]
已在 4.2.0 支持，增加 `__args__` 变量，可以从 env 中获取捕获的参数列表，需开启 `Options.CAPTURE_FUNCTION_ARGS`

https://github.com/killme2008/aviator/releases/tag/aviator-4.2.0

**Comment by killme2008** [comment]
更详细说明

https://github.com/killme2008/aviator/wiki/%E5%AE%8C%E6%95%B4%E9%80%89%E9%A1%B9%E5%88%97%E8%A1%A8%E8%AF%B4%E6%98%8E#capture_function_args
