### ISSUE TITLE
Avaitor并发问题

### ISSUE THREAD

**Issue by kongkong4556** [killme2008/aviator#129]
麻烦问下，如果使用情况为AviatorEvaluator.execute(fun1("a*b/c")/fun2("d*e/f")，env),此处的fun1和fun2都为自定义函数，里面的a,b,c,d,e,f都为因子，需要进入fun1和fun2中进行查询,如何才能保证线程安全呢？目前测试是无法满足的，感谢

**Comment by killme2008** [comment]
你的自定义函数需要自行保证线程安全。

**Comment by kongkong4556** [comment]
嗯嗯，我现在遇到的问题就是比如多线程中fun1("a*b/c")/fun2("d*e/f")但是发现在进入fun1中的对应的应该传入的是(1*2/3)但实际进入的参数却是其他线程的(4*5/6),不太清楚问题出在哪儿了，所以想请教您一下

**Comment by kongkong4556** [comment]
这里的“aa*bb/cc“都是字符串形式传进来的,想通过字符串形式先把一些基本公式传进函数里面，再在自定义函数里面获取aa,bb,cc的值然后计算

**Comment by killme2008** [comment]
是不是你传入的 env 是共用的？

**Comment by kongkong4556** [comment]
我在每个线程开始之前都都单独new的一个concurrentHashMap

**Comment by kongkong4556** [comment]
单独new的一个concurrentHashMap作为env的

**Comment by kongkong4556** [comment]
我再好好检查一下，十分感谢您的解答

**Comment by kongkong4556** [comment]
感谢您的提醒，我刚才又检查了一下env确实是您说的共用的问题，刚刚又试了一次就没问题了，十分感谢

**Comment by killme2008** [comment]
好的，我关闭了， aviator 引擎本身是线程安全的，只要你传入的 env 是线程安全的，你的自定义函数是线程安全的，那就没有问题。

**Comment by kongkong4556** [comment]
好的，感谢
