### ISSUE TITLE
如何获取函数及对应参数

### ISSUE THREAD

**Issue by kane-chen** [killme2008/aviator#131]
例如我有func1,func2 两个函数，这两个都是从远程获取数据的，
我又一个表达式是这个的
      ( func1(aaa) || func2(bbbb) ) 
&& ( func1(ccc) || func2(dddd) ) 
&& ( func1(eee) || func2(ffff) )

我希望在实际执行表达式前，获取func1需要获取aaa,ccc,eee的值；然后一次批量的获得；
然后再把对应值放到context去执行，这样可以将3次调用减少为一次调用；
有没有这样的API，实现从表达式中，获取某一个（指定的）函数对应的参数值

**Comment by killme2008** [comment]
sorry，我没有明白你的意思。

**Comment by kane-chen** [comment]
> sorry，我没有明白你的意思。

比如func1(ccc) 是检查某人有没有ccc的权限，func1(ccc)是一次远程的调用；
我想把func1的多次调用合并成一次调用，减少调用次数

**Comment by killme2008** [comment]
你可以在你的 func1 里做一层基于thread local 的 cache 即可，根据 arguments 来 cache result.

**Comment by kane-chen** [comment]
> 你可以在你的 func1 里做一层基于thread local 的 cache 即可，根据 arguments 来 cache result.

我需要先从表达式中获取到，func1需要校验那几个code；然后再把这几个code作为参数传过去；
从表达式提供func1的参数，这个现在没有api

**Comment by killme2008** [comment]
这个目前没有的。

**Comment by killme2008** [comment]
已在 4.2.0 支持，增加 `__args__` 变量，可以从 env 中获取捕获的参数列表，需开启 `Options.CAPTURE_FUNCTION_ARGS`

https://github.com/killme2008/aviator/releases/tag/aviator-4.2.0

**Comment by killme2008** [comment]
更详细说明

https://github.com/killme2008/aviator/wiki/%E5%AE%8C%E6%95%B4%E9%80%89%E9%A1%B9%E5%88%97%E8%A1%A8%E8%AF%B4%E6%98%8E#capture_function_args
