### ISSUE TITLE
对于分母为0的特殊处理

### ISSUE THREAD

**Issue by kongkong4556** [killme2008/aviator#133]
目前有需求想要对于a+b/c这种如果c为0的话就直接等于a的值 b/c为0，这种有比较好的建议实现的方式么？

**Comment by killme2008** [comment]
两种方法：
1. 修改表达式  `a+ (c ==0 ? 0: b/c)`
2. 重载除法运算符，参见  https://github.com/killme2008/aviator/wiki#%E9%87%8D%E8%BD%BD%E8%BF%90%E7%AE%97%E7%AC%A6

对被除数是0的情况做特别处理。

**Comment by kongkong4556** [comment]
收到，感谢

**Comment by killme2008** [comment]
好的，先关闭了，有问题再联系。
