### ISSUE TITLE
怎样重载三元操作符呢？

### ISSUE THREAD

**Issue by jimmyking** [killme2008/aviator#139]
你好，我想把“?:”重载成 “如果xxx则xxx否则xxxx”这样的操作符有什么办法吗？

**Comment by killme2008** [comment]
参见运算符重载

https://github.com/killme2008/aviator/wiki#%E9%87%8D%E8%BD%BD%E8%BF%90%E7%AE%97%E7%AC%A6

三元操作符对应的是 `Operator.TERNARY`
