### ISSUE TITLE
表达式中有函数,context中无参数 报错

### ISSUE THREAD

**Issue by tttMelody** [killme2008/aviator#14]
```java
String s = "timeHourRange(e1_startTime,0,13)";
Map< String, Object > context = new HashMap<>();
AviatorEvaluator.compile( expression, true ).execute( context );// expected false,actuall exception
```
这样执行就会抛异常,是因为没有e1_startTime参数 `Caused by: java.lang.NullPointerException: There is no string namede1_startTime`,这样的情况我想返回false,应该怎么做到呢?急急急啊

**Comment by tttMelody** [comment]
```java
    public AviatorObject call ( Map< String, Object > env, AviatorObject arg1, AviatorObject arg2, AviatorObject arg3 ) {
        if ( env.size() != 3 ) {
            return AviatorBoolean.FALSE;
        }
        ...
}
```

这么改了一下 可以返回false,不知道符不符合作者您的意图(或者作者也可以考虑加个这个判断呢?就是env的大小要和后面的arg数量一致)

**Comment by killme2008** [comment]
你好，你下面的改动是正确的，因为你的函数需要判断参数是不是 null。

**Comment by killme2008** [comment]
不过我可以为 AviatorObject 增加一个方法 isNil，来方便判断。

**Comment by killme2008** [comment]
马上发布 3.0.0 版本，增加 AviatorObject.isNull(env) 方法，方便判断。

**Comment by killme2008** [comment]
你好，已经发布 3.0.0

https://github.com/killme2008/aviator/releases/tag/aviator-3.0.0

maven 同步可能要明后天。

**Comment by tttMelody** [comment]
非常感谢作者的及时回答与优化
