### ISSUE TITLE
自定义函数嵌套调用顺序调整

### ISSUE THREAD

**Issue by kongkong4556** [killme2008/aviator#144]
麻烦问两个问题
第一个问题，调用自定义函数例如 fun1(fun2(b)),有办法自定义先执行fun1再执行fun2么？
第二个问题，有场景需要fun(a*b+c),调用自定义方法fun时a,b,c都包含多个元素，例如 <a,<1,2,3>>,<b,<4,5,6>>,<c,<7,8,9>>，想要实现(1*4+7)+(2*5+8)+(3*6+9),其中 a*b+c也可能会变成 d*f*e等等有比较好的实现方式么？目前我采用的是fun("a*b+c"),把这个a*b+c当做字符串传进函数里面然后获取参数执行的

**Comment by killme2008** [comment]
1. 没有办法，函数的参数都是先求值，后调用。
2. 没看明白问题。

**Comment by kongkong4556** [comment]
2的问题就是有一种场景，因子a里面是list里面有12个月份的值，因子b也是list12个月份的值
我想实现的就是比如有个自定义函数selfSum(a*b+a/b),这个意义是想实现逐个月都按照(a*b+a/b)然后再求和,这里面a*b+a/b这个公式不固定，可能是其他的，想问下有什么好的实现方法么

**Comment by killme2008** [comment]
重载操作符？

https://github.com/killme2008/aviator/wiki#%E9%87%8D%E8%BD%BD%E8%BF%90%E7%AE%97%E7%AC%A6

**Comment by kongkong4556** [comment]
应该解决不了，不是所有的加，减这些都要重载，只是想实现  a<1,2> b<3,4> selfFun(a*b+a/b) = (1*3+1/3)  +( 2*4+2/4)=10.83333这种的



在 2019-07-23 14:50:23，"dennis zhuang" <notifications@github.com> 写道：


重载操作符？

https://github.com/killme2008/aviator/wiki#%E9%87%8D%E8%BD%BD%E8%BF%90%E7%AE%97%E7%AC%A6

**Comment by killme2008** [comment]
那没有办法了，自定义函数吧

**Comment by kongkong4556** [comment]
我现在的做法是把selfFun("a*b+a/b"),"a*b+a/b"当做字符串传到自定义函数里面，然后在自定义函数中循环调用然后执行再求和做的

**Comment by kongkong4556** [comment]
只是想问您看看有没有什么更优的做法
