### ISSUE TITLE
使用aviator做schema校验疑问

### ISSUE THREAD

**Issue by MarcelLeon** [killme2008/aviator#148]
我目前通过aviator做数据清洗，大概是这个样子：
源数据形如：

> {
  key1:value1,
  key2:value2,
  son1List:[
    {
      key1:value1,
      key2:value2
    }
  ]
}

要求是 1）校验外层keys和son1List 里的keys对应value值是否符合schema，2）并且判断外层key1是否与son1List 内key1得值是否相等，那么会有这种方式 [比如schema规则是小于10]：
`表达式：key1 < 10 && key2 < 10 && son1List[0].key1 < 10 && son1List[0].key2 < 10 && key1 == son1List[0].key1`
我得问题是，这种表达式在量大时候，比如外层keys和son1List内得keys数量上百条时性能是否会形成问题？是建议用一个大的表达式，还是多个小的表达式性能更高？另：我之前采用得是hibernate validator得注解方式，但是原有方式不够灵活 schema规则支持有限比如不能支持上面说的要求2，想知道是否有过hibernate validator和aviator的效率对比呢？
多谢多谢

**Comment by killme2008** [comment]
key 的访问都是走 hashMap， O(1) 的复杂度，性能不是问题。数组访问也是。

**Comment by MarcelLeon** [comment]
知道了，谢谢
