### ISSUE TITLE
浮点数计算尾数控制

### ISSUE THREAD

**Issue by ChenLinXi** [killme2008/aviator#149]
- 问题描述
在不使用Decimal的情况下，浮点数计算时，存在部分小数点后尾数难以控制；

- 可优化点
Options添加浮点数精度控制；

- DEMO

        String exp = "math.ceil(price * 0.85)";

        Map<String, Object> input = new HashMap<>();
        input.put("price", 100.00);

        Object execute = AviatorEvaluator.execute(exp, input);
        System.out.println(execute);
其中math.ceil()为自定义函数，向上取整；

- 结果
测试结果：86.0
实际应该输出结果：85.0

**Comment by killme2008** [comment]
这是浮点数的特性，如果需要，你使用你说的类似 roundup 或者 ceil 函数。 aviator 本身不会去做这个事情。

**Comment by ChenLinXi** [comment]
已经了解到Aviator支持Decimal类型的自定义配置，
如果Aviator可以处理浮点数计算尾数导致的误差，这样程序的完成度会更高一些。

- Decimal配置

        AviatorEvaluator.setOption(Options.ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL, true);
        AviatorEvaluator.setOption(Options.MATH_CONTEXT, MathContext.DECIMAL32);

- 可能的优化点
支持浮点数小数精度的配置

- 浮点数计算DEMO

        String exp = "a - b";

        Map<String, Object> input = new HashMap<>();
        input.put("a", 5.2);
        input.put("b", 4.31);

        Object result = AviatorEvaluator.execute(exp, input);
        System.out.println(result);
        // 结果：0.8900000000000006
