### ISSUE TITLE
hi, 这个表达式无法正确解析(string.split('a,b,c,d',','))[1]

### ISSUE THREAD

**Issue by Jianwei-Wang** [killme2008/aviator#15]
结果是一个数组，无法获得第二个元素。我的用法有错误吗？还是不支持

**Comment by killme2008** [comment]
目前数组访问只允许变量，还没有支持函数的返回结果。

算是个 bug，会支持下。

**Comment by Jianwei-Wang** [comment]
好，感谢你提供这么优秀的开源软件

**Comment by killme2008** [comment]
@Jianwei-Wang  你好，已经发布 3.0.1， maven 同步可能需要一到两天，如果着急用，可以先下载二进制文件

https://github.com/killme2008/aviator/releases/tag/aviator-3.0.1

**Comment by Jianwei-Wang** [comment]
好，非常感谢
