### ISSUE TITLE
提取表达式中的变量？

### ISSUE THREAD

**Issue by Chanamper** [killme2008/aviator#153]
aviaotor是否支持针对需要执行的表达式进行其中的变量名提取呀？

**Comment by killme2008** [comment]
请问具体什么意思？

**Comment by Chanamper** [comment]
例如a+1==b这种表达式，提取其中的变量a和变量b

**Comment by killme2008** [comment]
`Expression#getVariablesNames()` 和 `Expression#getVariableFullNames()` 

http://fnil.net/aviator/apidocs/com/googlecode/aviator/Expression.html
