### ISSUE TITLE
support entry variable in map

### ISSUE THREAD

**Issue by yanmount** [killme2008/aviator#154]
how to loop inside a map, for example, filter a map in which value equals specified value:
like:
a=seq.map('k1', 'true', 'k2', 'v2');b=filter(a,entry.value.eq('true'))
hope that b=seq.map('k1', 'true')
thx

**Comment by yanmount** [comment]
essentially , there should be a special variable  to represent the item in the collection(or map)，provided that variable, above scenario would be fixed

**Comment by killme2008** [comment]
The filter function accepts a sequence and a predicate function as arguments. You can use lambda expression to define a predicate function:

```
a=seq.map('k1', 'true', 'k2', 'v2');b=filter(a, lambda(x) -> x.value == 'true' end)
```

**Comment by yanmount** [comment]
thx for quick answer, ur trick works, and another puzzle:
list=seq.list('1','2');map(list,lambda(x) -> send2Terminal(x,a) end)
but I cannot store the variable in "env" by calling env.put(k,v), whereas make it without lambda trick.
thx for feedback

**Comment by killme2008** [comment]
The `env` is a dynamic scope variable. When you leave the lambda body( after the `end`), the env is poped and you can't refer it any more.

If you want the side effect, maybe you should returns the value as the function result.

**Comment by yanmount** [comment]
thx for answering, your suggestion sounds works, although a little obscure, but maybe referring the inner item variable in collection directly as in scala is more intuitively and consistent
