### ISSUE TITLE
关于一键导入实例方法

### ISSUE THREAD

**Issue by lvlvforever** [killme2008/aviator#161]
4.2.3增加了一键导入类中的public的实例方法功能，能不能指定某些方法呢？
或者排除一些方法？考虑增加注解么？

**Comment by killme2008** [comment]
这个是可以考虑的，增加类似 `@Ignore` 的注解，甚至可以加上更复杂的，比如重命名

```
@Function(rename="is_blank")
public static boolean isBlank() {
....
}
```

**Comment by lvlvforever** [comment]
对的对的 老哥啥时候这个特性能安排上啊

**Comment by killme2008** [comment]
已经在 PR #163  实现了啊，不过不着急发。

**Comment by killme2008** [comment]
Release 4.2.4 
https://github.com/killme2008/aviator/releases/tag/aviator-4.2.4

新增三个 annotation:

* `Function` 设定方法导入后的函数名字
* `Ignore` 用于忽略导入。
* `Import` 设定一个 java class 导入的方法范围
