### ISSUE TITLE
suggestion that  the "map" method accepts map parameter

### ISSUE THREAD

**Issue by yanmount** [killme2008/aviator#164]
a=seq.map('k1', 'v1', 'k2', 'v2');
b=map(a,lambda(x) -> x.value end)
above code show the intention to convert a map to a list with only key or value, but encounter runtime error:
Caused by: java.lang.IllegalArgumentException: <JavaType, {k1=v1, k2=v2}, HashMap> is not a seq.
map variable can be considered as some kind of collection as map.entry. isn't

**Comment by killme2008** [comment]
Release 4.2.4 
https://github.com/killme2008/aviator/releases/tag/aviator-4.2.4
