### ISSUE TITLE
从3.3.0升级到4.1.2 AviatorDouble构造方法不兼容问题

### ISSUE THREAD

**Issue by yajieZou** [killme2008/aviator#165]
3.3.0版本AviatorDouble(Number number)是public
4.1.2版本AviatorDouble(Number number)只能同包下访问了

**Comment by killme2008** [comment]
请使用 AviatorDouble.valueOf 系列静态方法替代。

**Comment by killme2008** [comment]
也可以用 AviatorNumber. valueOf
