### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: Cannot cast java.lang.String to [Ljava.lang.String;

### ISSUE THREAD

**Issue by northsailorhjq** [killme2008/aviator#166]
public static String paren(String ...values) {
        StrBuilder sb= new StrBuilder(values);
        return "(" + sb.toStringAndReset() +")";
    }
调用此方法时报错，不支持多个参数

**Comment by killme2008** [comment]
请给出完整堆栈和详细信息，否则无从分析

**Comment by killme2008** [comment]
Release 4.2.4 
https://github.com/killme2008/aviator/releases/tag/aviator-4.2.4

Now you can call varidic method by:

```
ns.paren(seq.array(java.lang.String, 'hello', 'world'))
```
