### ISSUE TITLE
why asm

### ISSUE THREAD

**Issue by whdwsl** [killme2008/aviator#168]
hi, 首先感谢下作者，已用在生产环境，性能不错。为啥选择了asm生成字节码，而没有用JAVAASSIST，还有，从解析表达式到生成字节码这块代码逻辑没看太懂，比如有括号时，怎么判断执行的优先级？

**Comment by killme2008** [comment]
1. javaassit 背后也是 asm，这个库写的时候很早了，当时的目标是轻量级，所以不想再引入一层包装。
2. 优先级的问题，这个其实是一个很基本的递归下降解释器，具体有兴趣可以阅读下编译原理相关的书籍，比如《编译原理》第三版。
