### ISSUE TITLE
list过滤

### ISSUE THREAD

**Issue by saySunshine** [killme2008/aviator#17]
你好，aviator如何对list进行过滤？如：
```java
class Foo{
     private int i;
     private String m;
getter、setter……
}
List<Foo> list = new ArrayList<>();
list.add(new Foo(1,"m"));
list.add(new Foo(2,"n"));
list.add(new Foo(3,"n"));

//需要筛选出list中，i>2 && m=="n" 的list集合？
```

谢谢！

**Comment by killme2008** [comment]
使用 filter 函数：

`filter(seq,predicate)`

不过你这里的 predicate 可能需要自定义实现了。

参考

https://github.com/killme2008/aviator/wiki#%E5%86%85%E7%BD%AE%E5%87%BD%E6%95%B0
https://github.com/killme2008/aviator/wiki#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%87%BD%E6%95%B0
