### ISSUE TITLE
是否支持判断表达式是否成立"1<=3<9"

### ISSUE THREAD

**Issue by penweizgx** [killme2008/aviator#172]
规则匹配的时候，需要通过传入变量是否表达式成立，例如："1<=3<9"

**Comment by killme2008** [comment]
你这个表达式是不合法的，应该写成，逻辑表达式的语法跟 java 是一致的。

```
1<=3 && 3< 9
```

可以传入变量，参见开发指南
https://github.com/killme2008/aviator/wiki#%E4%BD%BF%E7%94%A8%E5%8F%98%E9%87%8F
