### ISSUE TITLE
3.2.0版本大量生成ClassLoader对象

### ISSUE THREAD

**Issue by danny18** [killme2008/aviator#174]
使用的版本为3.2.0，预编译了大量表达式后，发现内存中会有很多AviatorClassLoader对象，导致GC时间变长。查看源码发现：
![image](https://user-images.githubusercontent.com/6994197/68016648-f1670080-fccf-11e9-9bf7-e577f77547e8.png)
OptimizeCodeGenerator中每次编译对象时，会new一个新的ClassLoader出来。请问下这样做的好处是什么？为什么不使用生成好的aviatorClassLoader对象呢？
看了下最新版本的4.1.2，当cache设置为true的时候，不管是EVAL模式还是COMPILE模式，都用的是aviatorClassLoader。这是3.2.0版本里面的代码bug吗？

**Comment by killme2008** [comment]
3.2.0 版本已不再维护，建议升级。
