### ISSUE TITLE
表达式校验问题

### ISSUE THREAD

**Issue by hillfly** [killme2008/aviator#177]
版本：4.2.6
值：{"age ": 20}
表达式：$age >30 ($age < 20)

上述表达式能编译能编译通过，运行报错Could not cast object <Long, 0> into a aviator function.

同样的值和表达式，在2.3.7版本下编译报错。请问这类明显有问题的表达式能否在编译时就把异常抛出？

**Comment by killme2008** [comment]
这个应该是个bug，我会看下

**Comment by killme2008** [comment]
发布了 4.2.7，已修复。
