### ISSUE TITLE
表达式编译时报错

### ISSUE THREAD

**Issue by Chanamper** [killme2008/aviator#181]
![image](https://user-images.githubusercontent.com/19453117/70441986-56ccbf00-1ad0-11ea-9e07-b557fa0cc0d2.png)
请教一下，在使用aviator过程中，JDK版本采用1.8，传入不合法的表达式为(a1%2=0)&&(a2%2==0)时，出现VerifyError报错后进程退出，想要的结果是报错但进程不退出。

**Comment by killme2008** [comment]
你可以先 catch(Throwable t) 来解决，不过这个错误可以在编译阶段来捕获。

**Comment by Chanamper** [comment]
好的，我先这样处理，多谢哈。请教一下哈，看很多网上说这个问题是jar包依赖冲突的问题，但是查看maven依赖图没发现相关冲突jar包。

**Comment by killme2008** [comment]
@Chanamper 不是的，这是生成的字节码不对，可以在 parse 阶段就发现。

**Comment by Chanamper** [comment]
好的，多谢

**Comment by killme2008** [comment]
发布了 4.2.8。这个错误将以运行时异常的结果来报出，不会再以 Error 方式。由于 aviator 是一个 one pass 的 parser，这个错误暂时无法在编译期来报错。后续会想办法再改进下。
