### ISSUE TITLE
seq.list返回的数组无法修改

### ISSUE THREAD

**Issue by hug3id** [killme2008/aviator#187]
版本 v4.2.8

执行以下表达式
list = seq.list(2);list[0] = 3;list[0]

结果返回2

**Comment by killme2008** [comment]
目前还不支持类似 `x[i]=y` 这样的赋值，你可以暂时通过导入 `List` 类的实例方法来解决这个需求：

```java
 AviatorEvaluator.addInstanceFunctions("list", ArrayList.class);
    Long result =
        (Long) AviatorEvaluator.execute("list = seq.list(2);list.set(list, 0, 3);list[0]");
    System.out.println(result);
```

调用了 `ArrayList#set(index, value)` 方法

导入函数可以参见文档

https://github.com/killme2008/aviator/wiki/%E8%B0%83%E7%94%A8-Java-%E6%96%B9%E6%B3%95%E5%92%8C-Function-Missing

**Comment by killme2008** [comment]
发布了 4.2.9（可能要等一段时间才能从 maven central 同步到），已支持 `x[i] = y` 这样的数组或者 List 赋值。

https://github.com/killme2008/aviator/releases/tag/aviator-4.2.9
