### ISSUE TITLE
为何浮点数比较，小数位超过1位会比较错误

### ISSUE THREAD

**Issue by wanpeng19** [killme2008/aviator#188]
eg：  Double distance = 12.34

通过执行规则表达式 distance==12.34 会返回fasle

非要开启：
            AviatorEvaluator.setOption(Options.ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL, true);
才可以比较正常。

**Comment by killme2008** [comment]
浮点数有精度问题，遵循的都是 IEEE754 标准，怎么比较可以看

https://www.zhihu.com/question/67794172

https://www.jianshu.com/p/1d6ba0047a5b

BigDecimal 是 java 专门用来进行高精度运算的
https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html
