### ISSUE TITLE
数组 取值问题

### ISSUE THREAD

**Issue by xiurierye** [killme2008/aviator#19]
我有如下map 对象 
{
  "E": {
    "F": [
      {
        "H": 1,
        "J": {
          "A": 12
        }
      }
}
想取值 E.F[0].H 语法错误，
请问不支持数组map的嵌套取值吗？

**Comment by killme2008** [comment]
这个应该不支持，也不确定 beanutils 是否支持，如果有此类需求，暂时可以通过自定义函数来实现。

我会调研下。

**Comment by xiurierye** [comment]
非常感谢您的回答。

**Comment by killme2008** [comment]
我先开着，应该需要支持下。

**Comment by zuoerlost** [comment]
我也遇到了相同的需求。。。

**Comment by killme2008** [comment]
准备支持下这个特性了，但是引用这种类型的变量需要特殊的语法，类似 `$E.F[0].H`，前面多一个 dollar 符号，我晚上可能发布下。

**Comment by killme2008** [comment]
已经发布 3.1.0，maven 同步预计要明后天：

https://github.com/killme2008/aviator/releases/tag/aviator-3.1.0
