### ISSUE TITLE
【建议】是否能增加科学计数法、多行等新特性

### ISSUE THREAD

**Issue by hug3id** [killme2008/aviator#191]
感谢作者提供如此好用的脚本引擎！最近做一些数据处理方面的工作，例如下面通过aviator代码实现了分组操作：
```
list = seq.list(
    seq.map("年份", 2018, "气温", 20),
    seq.map("年份", 2019, "气温", 30),
);
groupingBy(list, lambda(v) -> v.年份 end, counting);
groupingBy(list, lambda(v) -> v.年份 end, summing(lambda(v) -> v.气温 end));
groupingBy(list, lambda(v) -> v.年份 end, averaging(lambda(v) -> v.气温 end));
groupingBy(list, lambda(v) -> v.年份 end, maxBy(lambda(v) -> v.气温 end));
groupingBy(list, lambda(v) -> v.年份 end, minBy(lambda(v) -> v.气温 end));
get = lambda(field) -> lambda(v) -> seq.get(v, field) end end;
groupingBy(list, get("年份"), counting);
```

函数实现：
```
// classifier = 分组依据，reduceOp = 聚集操作
groupingBy = lambda(list, classifier, reduceOp) ->
    list = reduce(list, lambda(container, v) ->
        key = classifier(v);
        item = seq.get(container, key);
        supplier = reduceOp.supplier; // 直接调用 reduceOp.supplier() 报错：函数不存在
        item = item == nil ? supplier() : item;
        accumulator = reduceOp.accumulator;
        item = v == nil ? item : accumulator(item, v);
        seq.add(container, key, item);
        container
    end, seq.map());
    finisher = reduceOp.finisher;
    finisher == nil ? list : map(list, lambda(e) -> seq.add(list, e.key, finisher(e.value)) end);list
end;

counting = make_reduce_op(
    lambda() -> 0 end,
    lambda(u, v) -> u + 1 end,
    nil
);

summing = lambda(mapper) -> make_reduce_op(
    lambda() -> 0 end,
    lambda(u, v) -> u + mapper(v) end,
    nil
) end;

averaging = lambda(mapper) -> make_reduce_op(
    lambda() -> tuple(0, 0) end,
    lambda(u, v) ->
        u[0] = u[0] + mapper(v);
        u[1] = u[1] + 1;
        u
    end,
    lambda(v) -> v[0] / double(v[1]) end
) end;

maxBy = lambda(mapper) -> make_reduce_op(
    lambda() -> -99999999999999999999 end, // 不支持科学计数法
    lambda(u, v) -> max(u, mapper(v)) end,
    nil
) end;

minBy = lambda(mapper) -> make_reduce_op(
    lambda() -> 99999999999999999999 end,
    lambda(u, v) -> min(u, mapper(v)) end,
    nil
) end;

make_reduce_op = lambda(supplier, accumulator, finisher) -> seq.map(
    "supplier", supplier != nil ? supplier : lambda() -> 0 end,
    "accumulator", accumulator != nil ? accumulator : lambda(u, v) -> u end,
    "finisher", finisher != nil ? finisher : identity
) end;
```

一些建议：
1. 能否支持多行的书写形式？目前看仅需要将换行字符替换为空格即可实现，能大大提高脚本可读性
2. 能否支持单行和多行注释？同样对调试代码帮助很大
3. 能否支持直接调用map中的函数？例如：m = seq.map("func", lambda()->0 end); m.func()，
目前需要这样：func = m.func; func()
4. 能否支持科学计数法，无法简洁表达很大或很小的数
5. 能否简化lambda 函数的定义，比如去掉lambda关键字？

非常感谢！

**Comment by killme2008** [comment]
感谢你的建议，我一一回答和确认下：

1. 现在就是支持多行的，只是需要分号，你的意思是说希望如果有换行符，就不需要分号？
2. 嗯，这个可以支持下
3. 这个也可以支持下，不过为了兼容，可能会需要引入一个选项开启。
4. 科学计数法是支持的啊，比如 `-9e10`，另外数字还支持十六进制(以0x或者0X开头的数字)。
5. 这个是目前的语法设计，暂时不考虑移除，有点类似 ruby 的 `begin end` 或者 clojure 的  `fn`。

**Comment by hug3id** [comment]
关于多行的问题，4.2.9版本运行 AviatorEvaluator.execute("a=3;\r\na+4"); 会报以下错误
Exception in thread "main" com.googlecode.aviator.exception.CompileExpressionErrorException: Aviator doesn't support multi-lines expression at 5
	at com.googlecode.aviator.lexer.ExpressionLexer.scan(ExpressionLexer.java:134)
	at com.googlecode.aviator.parser.ExpressionParser.move(ExpressionParser.java:840)
	at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:869)
	at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:855)
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:857)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:836)
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:948)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:519)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:531)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:552)

如果将换行符替换为空格就正常了，请验证。非常感谢！

**Comment by killme2008** [comment]
@hug3id  谢谢，明白你的意思了，会尽快修复下

**Comment by killme2008** [comment]
* [ ] 科学计数法 无法处理 `ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL` 选项。
* [ ] 换行符处理
* [ ] 函数调用支持变量语法糖

**Comment by killme2008** [comment]
发布了 4.2.10 https://github.com/killme2008/aviator/releases/tag/aviator-4.2.10

注释和 fn 的支持将放在 aviator script 分支  #199
