### ISSUE TITLE
compare-app-version(比较版本号)

### ISSUE THREAD

**Issue by smallbam** [killme2008/aviator#192]
how to mproved version number comparison？
eg：ver1="1.2.0"
        ver2="1.10.0"
ver1.compare(ver2) should return -1 but return 1

**Comment by killme2008** [comment]
The `version` is a string ,and character `1` is less than `2`, so `"1.2.0"` is greater than `"1.10.0"`.

You can define a custom function to do such comparision by convert the versions into number, see

https://github.com/killme2008/aviator/wiki#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%87%BD%E6%95%B0

**Comment by killme2008** [comment]
写了个简单例子，你可以直接用，假设版本号都是3个数字：

```java
 AviatorEvaluator.defineFunction("compare", "lambda(x, y) -> x > y ? 1 : (x == y ? 0 : -1) end");
    AviatorEvaluator.defineFunction("comp",
        "lambda(x, y) ->  xs =  map(string.split(x, '\\\\.'), long) ; ys = map(string.split(y,'\\\\.'), long);  a = compare(xs[0], ys[0]); b = compare(xs[1], ys[1]);  a == 0 ? (b == 0 ? compare(xs[2], ys[2]) : b) : a end ");

    System.out.println(AviatorEvaluator.execute("comp('1.10.0', '1.2.0')"));
```

**Comment by smallbam** [comment]
thank you, but lambda  is a little difficult for me.
