### ISSUE TITLE
有关异常处理

### ISSUE THREAD

**Issue by AJ-Liang** [killme2008/aviator#193]
在有些时候需要使用到异常处理分支，在这里，是否建议封闭成一个AviatorObject呢？

**Comment by killme2008** [comment]
能否举例说明？

**Comment by AJ-Liang** [comment]
例如后续可能会使用aviator来做虚拟服务的编排，虚拟服务的逻辑为：A-B-C，ABC三个服务同步按顺序调用，后一个服务请求参数来自前一个请求的返回。其间可能会有超时等异常出现，希望在表达式中能更友好地提供给服务开发者配置使用，所以语法需接近正常的服务调用JAVA代码。故会有正常返回值与异常处理。

**Comment by killme2008** [comment]
考虑支持下 try...catch

**Comment by killme2008** [comment]
发布了 5.0.0-RC2 支持了异常处理
https://github.com/killme2008/aviator/releases/tag/aviator-5.0.0-RC2

文档还待补充。
