### ISSUE TITLE
4.1.2 编译的速度偶尔会变得非常慢

### ISSUE THREAD

**Issue by codewyh** [killme2008/aviator#195]
编译速度偶尔会变得非常慢，随着时间出现的频率越来越高，最初基本都在1毫秒左右，但有时会增长到10几秒甚至几十秒，问题在本地无法复现。
这个是我们系统的耗时监控，期间gc都没有异常，这块的问题有可能出在哪里呢？
![image](https://user-images.githubusercontent.com/5165760/72596095-449f3580-3946-11ea-8a32-fe2053311ee5.png)

表达式基本都是如下形式：
((a == nil ? false : (a == 1)) || (((b == nil ? false : (b >= 6)) || (c == nil ? false : (c >= 10)))))
调用代码：
compiledExp = AviatorEvaluator.compile(aviatorExpr);

**Comment by killme2008** [comment]
是否编译的表达式过多？ 出现了 class unload 的情况，也就是 metaspace 的 full gc

**Comment by codewyh** [comment]
> 是否编译的表达式过多？ 出现了 class unload 的情况，也就是 metaspace 的 full gc

看监控是没有 class unload 和 full gc 的，这块还有可能是哪里出了问题呢

![image](https://user-images.githubusercontent.com/5165760/72673716-7086fc00-3aa9-11ea-8c22-3233f7c3b29c.png)

**Comment by killme2008** [comment]
@codewyh 是否是混部的系统？ 可能 cpu 被抢占？ 编译是耗费 cpu 的工作。

**Comment by killme2008** [comment]
有新的反馈再打开

**Comment by li-xiao-shuang** [comment]
> 是否编译的表达式过多？ 出现了 class unload 的情况，也就是 metaspace 的 full gc

我出现了这个情况  为什么在编译的时候这么耗费cpu？
