### ISSUE TITLE
如何获取逻辑运算表达式不成立的具体某子项表达式

### ISSUE THREAD

**Issue by godpit** [killme2008/aviator#197]
例如：表达式：A=='我'&&B==‘你’， 当这个表达式返回false的时候，如何获取具体那个判定条件出现了false导致返回false。

**Comment by killme2008** [comment]
你可以打开 trace，看到执行过程

https://github.com/killme2008/aviator/wiki/%E5%AE%8C%E6%95%B4%E9%80%89%E9%A1%B9%E5%88%97%E8%A1%A8%E8%AF%B4%E6%98%8E#trace_eval
