### ISSUE TITLE
aviator既然已经实现了ScriptEngine规范，就顺便提供一下the service provider啊

### ISSUE THREAD

**Issue by KingZxx** [killme2008/aviator#198]
![image](https://user-images.githubusercontent.com/12837999/73188972-a0e03180-415e-11ea-9831-16e3b2846488.png)

**Comment by killme2008** [comment]
可以的， 5.0.0-RC1 加下

**Comment by killme2008** [comment]
release 5.0.0-RC1 https://github.com/killme2008/aviator/releases/tag/aviator-5.0.0-RC1

相关文档 https://www.yuque.com/boyan-avfmj/aviatorscript/bds23b
