### ISSUE TITLE
过时的类无法卸载了。

### ISSUE THREAD

**Issue by sodalvjian** [killme2008/aviator#2]
测试了下，调用clearExpressionCache，清理后，应该用了加载器，这些丢弃的类都无法卸载呢。
类加载器是不是应该不要用一个，直接在生在字节码的时候NEW一个临时加载器，这样就可以卸载了。

**Comment by killme2008** [comment]
JVM 做 full gc 也会做 class unloading的， clearExpressionCache 是避免对 class 的强引用。

可以通过 -XX:+TraceClassUnloading 来观察类卸载。
