### ISSUE TITLE
变量语法糖在遇到NULL时无法完成字符串拼接

### ISSUE THREAD

**Issue by fengyizhu** [killme2008/aviator#200]
AviatorEvaluator.setOption(Options.NIL_WHEN_PROPERTY_NOT_FOUND,true);
对象a.b.c当b是null时，表达式 a.b.c +'abc' 报错；按照文档理解a.b.c当为null是应该返回nil才对？
期望计算结果是nullabc ，实际结果运行报错；
版本4.2.9

ExpressionRuntimeException: Could not add <JavaType, a.b.c, null, null> with <String, abc>

**Comment by killme2008** [comment]
看情况是个 bug

**Comment by killme2008** [comment]
已在 5.0.0 版本中修复。
