### ISSUE TITLE
如何区分变量是表达式内部自定义的还是外部输入的

### ISSUE THREAD

**Issue by 6768745e** [killme2008/aviator#202]
如下表达式：
```
b = a + 1
```
`a`是外部输入的变量，`b`是表达式内部自定义的变量

**Comment by killme2008** [comment]
目的是什么?

**Comment by 6768745e** [comment]
实际使用中，外部输入变量可能对应的是一个数据源或者一个计算结果。如果能区分出哪些是外部输入变量，那么一是可以提前校验表达式中是否使用了不合法的变量（不合法指的是没有对应的数据源或者计算过程），二是可以只计算表达式中使用到的变量值，而不是一股脑的把所有支持的数据源或计算结果都计算出来，这样可以减小构建env的代价。
从使用者角度来说，表达式就像一个函数或者一个脚本，输入与输出才是使用者比较关心的。内部变量就像class的private fields一样，只有表达式的创建者才需要考虑的，甚至都不应该暴露给使用者。

**Comment by 6768745e** [comment]
还有个问题：getVariableNames拿不到闭包捕获的变量，例如以下表达式：
```
map(list, lambda(v) v + u end)
```
getVariableNames只能返回`list`，但是`list`和`u`都是需要外部输入的。

**Comment by killme2008** [comment]
在 5.0.0 修复了这个 bug

https://github.com/killme2008/aviator/releases/tag/aviator-5.0.0-beta1
