### ISSUE TITLE
Aviator将express中所带的中横线 识别为了减法

### ISSUE THREAD

**Issue by z-Dapor** [killme2008/aviator#203]
如题：
例如自定义了一个query的func
方法 express： query(db-1,col1)
将会使得该func在执行的时候变成减法操作
请问该如何正确使用呢？

**Comment by killme2008** [comment]
- 号本身就是减号，变量名请符合 java 语法规则。

**Comment by z-Dapor** [comment]
例如执行function
date_to_string(date,format)
format = yyyy-MM-dd
那么这时候将会把format识别为减法。
该如何避免呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dennis zhuang <notifications@github.com&gt;
发送时间: 2020年2月26日 22:40
收件人: killme2008/aviator <aviator@noreply.github.com&gt;
抄送: z-Dapor <515944701@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[killme2008/aviator] Aviator将express中所带的中横线 识别为了减法 (#203)



 
号本身就是减号，变量名请符合 java 语法规则。

**Comment by killme2008** [comment]
字符串用引号括起来啊，文档里写了，单引号，双引号都可以
