### ISSUE TITLE
有一个问题1/2对于表达式引擎是否应该 等于 0.5,而不是沿用java 等于0

### ISSUE THREAD

**Issue by laisengui** [killme2008/aviator#204]
对于1/2.0 会自动转型 得到0.5
那么1/2 是否也应该自动转型 
或者条件判断 如果结果没有小数 仍旧沿用原来的类型 如果结果有小数则使用双精度

**Comment by killme2008** [comment]
你可以自行重载运算符

https://www.yuque.com/boyan-avfmj/aviatorscript/ra28g1#33329a38
