### ISSUE TITLE
两个集合相乘在reduce?

### ISSUE THREAD

**Issue by MacleZhou** [killme2008/aviator#205]
请教一个问题
有两个长度相同的数组或list如下：
a = [0, 1, 2, 3, 4, 5, 6];
b = [0, 1, 0, 1, 0, 1, 0];
如何计算: a[0]*b[0] + a[1]*b[1] + a[2]*b[2] ... a[n] * b[n]

我使用过 reduce( (a, b) -> a * b, +, 0)报错

**Comment by killme2008** [comment]
reducer 目前不支持这种用法，需要通过自定义函数实现。

**Comment by MacleZhou** [comment]
Thank you, I just self extended an DaulSeqReduceFunction to support this. Can I commit it? Or I send to you to commit.

**Comment by killme2008** [comment]
这个暂时不适合加入标准库，感谢
