### ISSUE TITLE
多参数方法会出现类型转换异常

### ISSUE THREAD

**Issue by z-Dapor** [killme2008/aviator#207]
例如
AviatorEvaluator.addStaticFunctions("str", StringUtils.class);
 val s = "{\n" +
                "    \"name\":\"xiaoming\",\n" +
                "    \"course\":\"math\",\n" +
                "}";
val jsonObject = JSON.parseObject(s);
Expression ex = AviatorEvaluator.compile("str.isAnyBlank(name,course)");
        Object execute = ex.execute(jsonObject);
        System.out.println("test："+execute5);
报错ClassCastException: Cannot cast java.lang.String to [Ljava.lang.CharSequence;

**Comment by z-Dapor** [comment]
Map<String,Object> res  = new HashMap<>();
        res.put("name","xiaoming");
        res.put("course","math");
        Expression ex5 = AviatorEvaluator.compile("str.isAnyBlank(name,course)");
        Object execute5 = ex5.execute(res);
        System.out.println("test5："+execute5);

**Comment by killme2008** [comment]
你说的是不定参数方法？

需要用数组的方式，参考  https://www.yuque.com/boyan-avfmj/aviatorscript/ra28g1#16243fbe

```
str.isAnyBlank(seq.array(java.lang.String， name, course))
```

**Comment by z-Dapor** [comment]
> 你说的是不定参数方法？
> 
> 需要用数组的方式，参考 https://www.yuque.com/boyan-avfmj/aviatorscript/ra28g1#16243fbe
> 
> ```
> str.isAnyBlank(seq.array(java.lang.String， name, course))
> ```

感谢，准备来close；我刚翻到这个文档，已经改好了

**Comment by killme2008** [comment]
这里后面可以去做个优化，自动包装下数组。
