### ISSUE TITLE
为什么执行表达式时的cache默认是关闭的？

### ISSUE THREAD

**Issue by Planeswalker23** [killme2008/aviator#211]
执行效率很低，最后发现没开cache，哭了。不传cache参数就默认关闭是有什么性能原因吗。。

**Comment by killme2008** [comment]
因为 cache 本质上是一种副作用（占用内存），还是希望用户明确开启，知道自己在做什么比较好，后面在文档会强调。

**Comment by Planeswalker23** [comment]
我看到您是把 Expression 保存在一个 ConcurrentHashMap 的，这会占用很大的内存吗？对于一般的 SpringBoot 应用程序来说应该是可以接受的吧。

如果把解析后的 Expression 类设置一个超时时间怎么样？长时间不使用就释放掉。

**Comment by Planeswalker23** [comment]
> 因为 cache 本质上是一种副作用（占用内存），还是希望用户明确开启，知道自己在做什么比较好，后面在文档会强调。

我看到您是把 Expression 保存在一个 ConcurrentHashMap 的，这会占用很大的内存吗？对于一般的 SpringBoot 应用程序来说应该是可以接受的吧。

如果把解析后的 Expression 类设置一个超时时间怎么样？长时间不使用就释放掉。

**Comment by killme2008** [comment]
@Planeswalker23 占用多大取决于用户有多少个表达式，这是不确定的。

**Comment by Patrick0308** [comment]
@killme2008 如果不开启缓存感觉效率太低了，是否可以考虑使用LRU控制占用内存大小，让用户控制缓存区的大小
