### ISSUE TITLE
含有if的表达式，上下文中缺少部分变量

### ISSUE THREAD

**Issue by zhoupj** [killme2008/aviator#212]
### case.  
```
@Test
    public void testIfElseVar() {

        String r1 = "result=true;v1='test1'; if(!result) {return 'ok';} v2='test2';  result";
        Map<String,Object> env=new HashMap<>();
        Assert.assertTrue((boolean)AviatorEvaluator.execute(r1,env));
        System.out.println(JSON.toJSONString(env));
    }
```

### result
```
{"result":true,"v1":"test1"}
```

* v2 没有出现，好像是if-else 后面的语句变量都不会出现。

**Comment by killme2008** [comment]
thank you ，这是个bug，我尽快修复下。你是需要依赖赋值的副作用？

**Comment by zhoupj** [comment]
主要作用是在执行错误的时候可以看到每个变量的值。 另外{} 中的变量【let和非let变量】也显示不了，局部作用域和全局作用域的变量，看看是否都可以展示出来呢？

**Comment by killme2008** [comment]
哦，如果是为了看过程中的，可以打印 `__env__` 变量，这个目前只是影响最终的副作用。

```
result=true;v1='test1'; if(!result) {return 'ok';} v2='test2'; println(__env__); result
```

**Comment by killme2008** [comment]
另外有 `Options.TRACE_EVAL` 选项可以看执行过程，这个选项会丰富下，加上条件语句和循环等指令。

**Comment by zhoupj** [comment]
加这个‘println(__env__)’ 有点不太合适，

**Comment by killme2008** [comment]
@zhoupj 这个问题已经修复，你说的 let 的问题，是否给个例子重现？

**Comment by killme2008** [comment]
这个修复还带来性能提升了 30%，感谢反馈啊

**Comment by zhoupj** [comment]
let 的问题实际是这个意思： if(xxx){let v4='test4'; }     v4 能不能也呈现到 最后的上下文中？【配置一个选项控制？】 。   

修复的已经release 了吗？

**Comment by killme2008** [comment]
@zhoupj  这个没办法，这个不符合作用域的语义，不过你可以通过传入一个 map，然后明确 seq.set(m, k, v) 来明确设置。

修复没有 release，在 master 分支。

**Comment by killme2008** [comment]
release 5.0.0-beta2
