### ISSUE TITLE
自定义函数的使用问题

### ISSUE THREAD

**Issue by tyrui** [killme2008/aviator#215]
1.java静态方法和实例方法的注册，相对基于AviatorFunction接口的实现类的做法，是不是第一种的性能比较差？
2.java静态方法注册
类1：
public class TestFunction {
   public static void neq(){
        System.out.println("test.neq 0 args");
    }
    public static void eq(){
        System.out.println("test.eq 0 args");
    }
}
类2：
public class TestFunction2 {
    public static void neq(Object a){
        System.out.println("test2.neq 1 args");
    }
    public static void gt(Object a,Object b,Object c){
        System.out.println("test2.gt 3 args");
    }
}
注册： 
AviatorEvaluator.addStaticFunctions("test", TestFunction.class); AviatorEvaluator.addStaticFunctions("test", TestFunction2.class);
遇到的问题：
1.TestFunction2 .neq(objject a) 覆盖了TestFunction .neq()；（参数个数不同也会被后注册的(namespace+同名)覆盖)
2.TestFunction.eq()这样的，可被随意个参数的调用，比如test.eq()、test.eq(1)、test.eq(1,2,3)....
3TestFunction2.gt(Object a,Object b,Object c)这样的调用时候，参数个数小于3个时候：ArrayIndexOutOfBoundsException异常；大于等于3个时候都可以被正常调用

3.脚本执行的过程中，变量是被保存在evn中，print和println的不知道能不能被保存，这样如果实现图形化界面配置的时候，test时候是可预览的

4.请问大佬，这个目前有没有图形化操作的案例啊？或者有没有支持AST（或者JSON树）的案例啊？

**Comment by killme2008** [comment]
1. 是的， 导入的方法是基于反射，相比实现 AviatorFunction（继承 `AbstractFunction` 更方便），性能上有3倍的差距，但是大部分情况下已经足够，你可以自行测试下是否满足你的系统要求。

2. 会覆盖，请用不同的 namespace 或者合并两个类。
3. 第三个问题没看明白，是说不定参数？需要用数组，参见 https://www.yuque.com/boyan-avfmj/aviatorscript/ra28g1#16243fbe
4. 可以开启 `Opitons.TRACE_EVAL` 选项查看执行过程，图形化暂未支持 https://www.yuque.com/boyan-avfmj/aviatorscript/yr1oau#TRACE_EVAL

**Comment by tyrui** [comment]
第三个问题我重新描述一下，
1.定义了方法test.doit（），并且该命名空间下该方法没有重载的情况下，脚本调用可任意多个参数调用该方法
2.定义了方法test.doit(arg1,arg2),并且该命名空间该方法重载的情况下，脚本调用时候入参大于等于两个时候和上面问题相同，小于两个时候抛数组下标越界的异常
ps：另外两个问题
if语法支持if（ture），循环不支持（），强迫症的人真是难受啊😂
2.wiki上写的，深层嵌套变量比如#map.list[0].name，我这边测试不支持的，必须要用#map.list.[0].name的写法

**Comment by killme2008** [comment]
```
2.wiki上写的，深层嵌套变量比如#map.list[0].name，我这边测试不支持的，必须要用#map.list.[0].name的写法
```
这个应该文档错了，我看看哪里没有纠正过来

```
if语法支持if（ture），循环不支持（），强迫症的人真是难受啊😂
```

while(true) 支持啊
```js
if语法支持if（ture），循环不支持（），强迫症的人真是难受啊😂
```


```
.定义了方法test.doit（），并且该命名空间下该方法没有重载的情况下，脚本调用可任意多个参数调用该方法
2.定义了方法test.doit(arg1,arg2),并且该命名空间该方法重载的情况下，脚本调用时候入参大于等于两个时候和上面问题相同，小于两个时候抛数组下标越界的异常
```

这个问题我看下

**Comment by killme2008** [comment]
文档没有错啊：

```
对于一些深度嵌套的 List 或者数组的访问， commons-beanutils还支持类似 #map.array.[0].name这样的访问语法，如果不满足JavaBean规范的，请尝试使用这样的语法做嵌套访问。
```

https://www.yuque.com/boyan-avfmj/aviatorscript/ra28g1#d72b8815

**Comment by tyrui** [comment]
> 文档没有错啊：
> 
> ```
> 对于一些深度嵌套的 List 或者数组的访问， commons-beanutils还支持类似 #map.array.[0].name这样的访问语法，如果不满足JavaBean规范的，请尝试使用这样的语法做嵌套访问。
> ```
> 
> https://www.yuque.com/boyan-avfmj/aviatorscript/ra28g1#d72b8815

😂看错了，原来写的是'并不支持'#map.list[0].name的写法

**Comment by tyrui** [comment]
for循环不支持（），毕竟大部分情况下用for的啊

**Comment by killme2008** [comment]
> for循环不支持（），毕竟大部分情况下用for的啊

`for x in y` 是比较符合自然的，if和 while 也提倡不要加括号，这一点是跟 rust 学习的。

**Comment by tyrui** [comment]
大佬，有没有交流群啊，这边还是不适合请教问题的

**Comment by killme2008** [comment]
> 大佬，有没有交流群啊，这边还是不适合请教问题的

暂时没有，我个人也不喜欢 IM 交流，邮件列表或者 issue 的方式更好，打扰比较少，信息比较聚焦。

**Comment by killme2008** [comment]
建了个顶顶群，可以加这个 30739878

**Comment by tyrui** [comment]
> 建了个钉钉群，可以加这个 30739878

好的，收到，大佬阿里的啊
