### ISSUE TITLE
如何手动销毁已编译的Expression

### ISSUE THREAD

**Issue by QuailOurs** [killme2008/aviator#218]
您好, 目前我这边需要频繁的更新表达式, 所以会定时更新编译一批表达式, 已开启缓存模式, 但是仍然容易出现表达式对象过多导致的OOM, 请问有什么方法可以直接手动销毁Expression对象吗?

**Comment by killme2008** [comment]
你的 jvm 版本？

**Comment by QuailOurs** [comment]
JVM: Java HotSpot(TM) 64-Bit Server VM (25.66-b17, mixed mode)
Java: version 1.8.0_66, vendor Oracle Corporation
Java Home: /opt/soft/jdk/jdk1.8.0_66_256/jre
JVM Flags: <none>

        <dependency>
            <groupId>com.googlecode.aviator</groupId>
            <artifactId>aviator</artifactId>
            <version>4.2.10</version>
        </dependency>

**Comment by killme2008** [comment]
JDK8 及以上默认用的是 jvm lambda 的生成机制，Unsafe#defineAnonymousClass 生成的匿名类，理论上当 expression 实例无引用后会被回收。  但是如果你启用了 aviator.preferClassloaderDefiner=true 的话，会使用传统的 classloader 定义，这种情况下需要将整个 AviatorEvaluatorInstance 丢弃才可以，AviatorEvaluatorInstance后续会提供一个重新设置 classloader 的 api

**Comment by killme2008** [comment]
@QuailOurs 你这里更多是因为缓存的对象过多引起的，可以通过 `invalidateCache(expression)` 来主动移除缓存，缓存移除后，对应的匿名类会回收。

**Comment by killme2008** [comment]
当然，更粗暴的可以丢掉老的，重建整个 AviatorEvaluatorInstance

**Comment by Mike0534** [comment]
> @QuailOurs 你这里更多是因为缓存的对象过多引起的，可以通过 `invalidateCache(expression)` 来主动移除缓存，缓存移除后，对应的匿名类会回收。清理所有的缓存，可以调用 `clearExpressionCache`。当然前提是你没有启用 `aviator.preferClassloaderDefiner=true`，否则就只有重建下 AviatorEvaluatorInstance

个人建议：能否提供LRU机制的缓存方案呢？我们缓存用Caffeine用的比较多，感觉也很方便，可以提供类似的方式。

**Comment by killme2008** [comment]
增加了

https://github.com/killme2008/aviator/commit/40079abb07f53d32ffac9a71e699669b925992de

**Comment by Mike0534** [comment]
> 增加了
> 
> [40079ab](https://github.com/killme2008/aviator/commit/40079abb07f53d32ffac9a71e699669b925992de)

给力！

**Comment by QuailOurs** [comment]
@killme2008 十分感谢, 之前我的问题定位与描述有误, 目前问题已经解决, 原因是由于业务需要频繁编译表达式而没有及时使用invalidateCache(expression)清理缓存导致Metaspace OOM.

**Comment by killme2008** [comment]
release 5.0.0-RC1 https://github.com/killme2008/aviator/releases/tag/aviator-5.0.0-RC1

增加了一些 classloader 的操作 API
