### ISSUE TITLE
When parsing long Number, it can't correctly judge overflow

### ISSUE THREAD

**Issue by H123R** [killme2008/aviator#219]
**Version**: 
4.2.10
**code**:
String num = "27670116110564327423"; // 2E63 + 2E64 - 2
System.out.println(num.equals(AviatorEvaluator.execute(num).toString())); //It will print false;

**Position**:
com.googlecode.aviator.lexer.ExpressionLexer#scan(boolean) 
if (lval < 0) {   //row 261
          isOverflow = true;
}

**Reason**:
Out of range not means is negative.

**Fix**:
![image](https://user-images.githubusercontent.com/26280647/78357943-f0226280-75e4-11ea-8fc7-0ad8476d2703.png)

**Comment by H123R** [comment]
Fix-Add:
![8987e1ca645809d94fcb48745182732](https://user-images.githubusercontent.com/26280647/78358811-64113a80-75e6-11ea-8f3a-7318ad0a597f.png)

**Comment by killme2008** [comment]
@H123R  Good catch, can you create a PR? Thanks a lot

**Comment by H123R** [comment]
OK

**Comment by killme2008** [comment]
Release 5.0.0-RC1
https://github.com/killme2008/aviator/releases/tag/aviator-5.0.0-RC1
