### ISSUE TITLE
关于类型的问题

### ISSUE THREAD

**Issue by hxwabc** [killme2008/aviator#22]
1. 为什么不加一个integer类型, 这个大家可能更常用, 更习惯. 虽然Long已经可以实现相关的内容了.
2. 参数加入json对象的支持, 现在这种数据类型也比较常用.
3. string相关的函数中没有考虑到null的情况, 能否用common-lang中的函数代替. 或者我改好后提request.

**Comment by killme2008** [comment]
1. 统一为 long 是方便后端处理。
2.传入的变量可以是 map 和 java POJO，literal 的不准备支持。
3. 欢迎提 PR。
