### ISSUE TITLE
执行aviator表达式发生线程Block问题

### ISSUE THREAD

**Issue by archervanderwaal** [killme2008/aviator#222]
### 背景
我们有个线程池专门用于执行各种aviator表达式，最近发现线上机器时不时会发生线程block的现象，如下图所示：
![image](https://user-images.githubusercontent.com/18182408/78654384-038c4100-78f7-11ea-8a4d-a7fd3a60dae6.png)

**Comment by archervanderwaal** [comment]
发现是在Aviator表达式执行的时候，如果是嵌套类型，就会去先get BeanUtilsBean对象，获取这个对象的时候是加了锁的，导致线程经常会block在这里。

**Comment by killme2008** [comment]
版本是多少？

**Comment by archervanderwaal** [comment]
2.3.3

**Comment by killme2008** [comment]
这个版本太老了，建议升级下到 4.x 版本，或者可以单独将 commons-beanutils 升级下。

**Comment by archervanderwaal** [comment]
看了一下最新版本的commons-beanutils对于BeanUtilsBean的实现没有什么改动，所以这块应该还是会出现线程block的情况

**Comment by killme2008** [comment]
aviator 有做了一些优化，针对 map 类型。这里 beanutils 的实现太差了，后续我看下怎么弄进来改进下。

**Comment by archervanderwaal** [comment]
我们刚做了个测试，多线程下针对表达式没有嵌套类型和有嵌套类型的表达式，发现执行有嵌套类型的表达式比没有嵌套类型的表达式慢近100倍。

**Comment by killme2008** [comment]
@archervanderwaal 慢是一定的，因为他是反射的。不过这里他慢的原因还是 beantuils 这把锁。正常反射的差距应该在 3~5 倍。如果短期内你们无法升级，可以先通过展开变量来解决下。

**Comment by killme2008** [comment]
可以参考我这个实现

https://github.com/killme2008/aviator/commit/2b10b28affbd4215c24411f65ee66bc443dff535

移除了全局锁

**Comment by archervanderwaal** [comment]
好的，谢谢~

**Comment by killme2008** [comment]
release 5.0.0-RC1 https://github.com/killme2008/aviator/releases/tag/aviator-5.0.0-RC1
