### ISSUE TITLE
能否支持未命中表达式结果输出

### ISSUE THREAD

**Issue by hillfly** [killme2008/aviator#223]
已知脚本:  age > 3 && lastName != 'ABC' && nickName != 'CDA'
传参：age=4, lastName = 'CCC', nickName ='CDA'
脚本运行结果为false，希望还能返回未命中的子表达式，比如 lastName != 'ABC' 。

我知道目前有trace模式可以通过观察执行过程来判断，但是实际使用不太灵活。我这边希望能记录每一次请求未命中的子表达式，方便后续分析。

**Comment by killme2008** [comment]
这里的需求也是过于定制化，你这里应该都是布尔表达式吧，比较建议是不是可以通过重载所有的比较运算符来解决，当比较的结果为 false 的时候，将参数打印到日志。
