### ISSUE TITLE
自定义函数内部只能调用默认实例进行计算

### ISSUE THREAD

**Issue by Mike0534** [killme2008/aviator#226]
您好，我定义了一个求和函数sigma , 如图：
![image](https://user-images.githubusercontent.com/25402867/79224378-8e3be580-7e8d-11ea-89b9-6790fcc1f7a7.png)
为了能够嵌套调用，内部使用 默认实例 做了一次解析计算。
但是在实际调用的时候，通过newInstance获取实例来计算的方式会报错：
![image](https://user-images.githubusercontent.com/25402867/79224450-aca1e100-7e8d-11ea-9caa-1f2d8d309eac.png)
报错信息如下：
![image](https://user-images.githubusercontent.com/25402867/79224474-b75c7600-7e8d-11ea-95bd-89499f734069.png)
请问：自定义的函数，如果需要计算的话，只能使用默认的单例么？
aviator version： 4.2.10
os：Windows 10 pro
openjdk version: 1.8.0_212-3-redhat

**Comment by killme2008** [comment]
这是因为 instance 的上下文不一样啊，newInstance 是一个新的引擎，他跟全局是两个。
这里的解决办法是从 env 里获取当前的 instance:

```java
import com.googlecode.aviator.runtime.RuntimeUtils;
....

RuntimeUtils.getInstance(env).execute(sumExp.toString, ....)

```

**Comment by Mike0534** [comment]
明白了，但是我刚刚在github上提交了这个问题。好尴尬。。。
















在 2020-04-14 19:40:50，"dennis zhuang" <notifications@github.com> 写道：

这是因为 instance 的上下文不一样啊，newInstance 是一个新的引擎，他跟全局是两个。
这里的解决办法是从 env 里获取当前的 instance:

importcom.googlecode.aviator.runtime.RuntimeUtils;

....RuntimeUtils.getInstance(env).execute(sumExp.toString, ....)
