### ISSUE TITLE
在使用openJ9jvm执行表达式引擎的时候会导致程序crash

### ISSUE THREAD

**Issue by workasprogrammer** [killme2008/aviator#228]

**Comment by workasprogrammer** [comment]
在使用openj9时调用 
Map<String,Object> map = new HashMap();
        map.put("param1","1");
        map.put("param2","1");
        System.out.println(AviatorEvaluator.execute("param1==param2", map, true));
异常如下：
07:38:12.081 0x3189a00   j9jcl.189    *   ** ASSERTION FAILED ** at common/sun_misc_Unsafe.cpp:73: ((constPatches == 0))
导致程序崩溃

**Comment by killme2008** [comment]
加上环境变量：  -Daviator.preferClassloaderDefiner=true

或者代码中启动的位置设置：

```java
System.setPropertity("aviator.preferClassloaderDefiner", "true");
```

参考 https://www.jianshu.com/p/fb8b8e541138

应该是 IBM JDK 的 unsafe 支持和 oracle jdk 不同。

**Comment by workasprogrammer** [comment]
可以了，感谢大佬！

**Comment by killme2008** [comment]
这个准备做个自动判断
