### ISSUE TITLE
全局数字设置为decimal时，脚本中的自定义数字解析编译出错！

### ISSUE THREAD

**Issue by Fernando-Zh** [killme2008/aviator#233]
在实例初始化时，应用如下配置（将所有数字识别为bigdecimal）
        instance.setOption(Options.ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL, true);
        instance.setOption(Options.ALWAYS_PARSE_INTEGRAL_NUMBER_INTO_DECIMAL, true);
编写脚本后编译报错，代码如下：
let taxPointList = tuple(0, 0.1, 0.2, 0.25, 0.3, 0.35, 0.45);
let index = 0;
for item in taxPointList{ 
if (index == 2) {
continue; ## 注意，这里貌似也有错
}
index = index  +1;
}

影响版本：5.0.0-RC2

**Comment by killme2008** [comment]
解析并没有报错，能否将报错信息附上

**Comment by killme2008** [comment]
continue 也没问题的，你的代码写的有问题， index = 2 之后就没有递增了，永远等于 2 直到循环结束。

**Comment by killme2008** [comment]
稍微改下就能看出来：

```js
let taxPointList = tuple(0, 0.1, 0.2, 0.25, 0.3, 0.35, 0.45);
let index = 0;
for item in taxPointList{
  p(item + " , index=" + index);
  if (index == 2) {
    continue; ## 注意，这里貌似也有错
  }
  index = index +1;
}

```

输出：
```text
0 , index=0
0.1 , index=1
0.2 , index=2
0.25 , index=2
0.3 , index=2
0.35 , index=2
0.45 , index=2
```

有问题再反馈吧，我先关闭了。另外建议升级到 5.0 版本，已经发布了。
