### ISSUE TITLE
AviatorEvaluator.execute执行完后，怎么知道修改了env参数(Map)里的哪些值

### ISSUE THREAD

**Issue by bingxueyinlian** [killme2008/aviator#234]
执行AviatorEvaluator.execute(String expression, Map<String, Object> env)方法后，怎么知道修改了env参数(Map)里的哪些值，因为要对修改过的值做日志记录。现在只能在调用前对Map进行备份，执行后两个Map做对比。请问，有没有更直接一点的获取被修改过的字段的方法？

**Comment by killme2008** [comment]
hi，这个要做很容易的，你可以自己继承 HashMap实现一个自己的 map，覆盖其中的 put 方法，将key单独保存到一个 hash set 即可啊。
