### ISSUE TITLE
env环境变量中的_fas_赋值不正确

### ISSUE THREAD

**Issue by 48929645** [killme2008/aviator#236]
在执行类似(fun1(arg1)+fun2(arg2))/(func3()-1)这种表达式时发现在fun3函数中通过FunctionUtil.getFunctionArguments()方法获取当前函数的参数信息时，env对象中key=_fas_的值未更新，导致获取的是前一个函数的参数，本例中获取的是arg2，还请定位解决一下

**Comment by 48929645** [comment]
补充 一下测试代码，版本是5.0

import com.googlecode.aviator.AviatorEvaluator;
import com.googlecode.aviator.Options;
import com.googlecode.aviator.runtime.FunctionArgument;
import com.googlecode.aviator.runtime.function.AbstractVariadicFunction;
import com.googlecode.aviator.runtime.function.FunctionUtils;
import com.googlecode.aviator.runtime.type.AviatorBigInt;
import com.googlecode.aviator.runtime.type.AviatorObject;

import java.util.List;
import java.util.Map;

/**
 * @date 2020/5/11
 */
public class AviatorArgsTest {
    public static void main(String[] args) {
        //注册函数
        AviatorEvaluator.setOption(Options.CAPTURE_FUNCTION_ARGS, true);
        AviatorEvaluator.setOption(Options.ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL, true);
        AviatorEvaluator.setOption(Options.ALWAYS_PARSE_INTEGRAL_NUMBER_INTO_DECIMAL, true);
        AviatorEvaluator.addFunction(new AddFunction());
        AviatorEvaluator.addFunction(new SumFunction());
        System.out.println(AviatorEvaluator.execute("add(11111)+sum()"));           // 3.0
//        System.out.println(AviatorEvaluator.execute("add(add(1, 2), 100)")); // 103.0
    }
}

class AddFunction extends AbstractVariadicFunction {
    @Override
    public AviatorObject variadicCall(Map<String, Object> env, AviatorObject... args) {
        List<FunctionArgument> params = FunctionUtils.getFunctionArguments(env);
        for (FunctionArgument functionArgument : params) {
            System.out.println(getName()+":"+functionArgument.getIndex() + "," + functionArgument.toString());
        }
        return new AviatorBigInt(1);
    }

    public String getName() {
        return "add";
    }
}


class SumFunction extends AbstractVariadicFunction {
    @Override
    public AviatorObject variadicCall(Map<String, Object> env, AviatorObject... args) {
        List<FunctionArgument> params = FunctionUtils.getFunctionArguments(env);
        for (FunctionArgument functionArgument : params) {
            System.out.println(getName()+":"+functionArgument.getIndex() + "," + functionArgument.toString());
        }
        return new AviatorBigInt(1);
    }

    public String getName() {
        return "sum";
    }
}

**Comment by 48929645** [comment]
输出结果如下：
add:0,FunctionArgument [index=0, expression=11111]
sum:0,FunctionArgument [index=0, expression=11111]
2

**Comment by killme2008** [comment]
这个特性建议不要再依赖，这个问题我会看下，后面这个特性将使用 macro 宏的方式来替代。

**Comment by killme2008** [comment]
Release 5.0.1 https://github.com/killme2008/aviator/releases/tag/aviator-5.0.1
