### ISSUE TITLE
map操作取值时的问题

### ISSUE THREAD

**Issue by hxwabc** [killme2008/aviator#24]
public void testMap() {
        Map mmap = new HashMap<>();
        mmap.put("a", "1");
        mmap.put("b", "2");
        mmap.put("c", "3");
        mmap.put("100", "1001");

        Map<String, Object> env = new HashMap<String, Object>();
        env.put("map", mmap);

        // collect
        logger.info("☆☆☆ result = {}", AviatorEvaluator.execute("map.a", env));
        // error
        logger.info("☆☆☆ result = {}", AviatorEvaluator.execute("map.100", env));
    }

**Comment by hxwabc** [comment]
同样当我的key是数据是一样有问题. 
还有key是一个对象的属性  map.(foo.i), 也就是foo.i做为key. 与3.1.0新发布的嵌套不同, 这个需求是先要算key.
总而言之, key是一个变量, 并不是例子中的常量.    

    public void testMapArray() {
        Map map = new HashMap<>();
        map.put("a", "1");
        map.put("b", "2");
        map.put("c", "3");

        String[] arrData = new String[3];
        arrData[0] = "a";
        arrData[1] = "b";
        arrData[2] = "c";

        Map<String, Object> env = new HashMap<String, Object>();
        env.put("map", map);
        env.put("arrData", arrData);

        // collect
        logger.info("☆☆☆ result = {}", AviatorEvaluator.execute("map.a", env));
        // error
        logger.info("☆☆☆ result = {}", AviatorEvaluator.execute("map.arrData[0]", env));
    }

**Comment by hxwabc** [comment]
试了各种写法都不行, 可能要自己写函数了.

**Comment by killme2008** [comment]
不好意思，你说的问题是什么问题，我没搞清楚。如果说 map 的  key 是需要计算的，抱歉，这个是不支持的。

**Comment by hxwabc** [comment]
第一个问题, key是数值时有问题. 比如map.100
第二个问题是key需要计算, 这个我通过自定义函数去实现了.

**Comment by yangsj19870829** [comment]
map取值确实有问题，遇到一样的问题。  拿这个样例直接跑，报错。
https://github.com/killme2008/aviator/blob/master/src/test/java/com/googlecode/aviator/example/CollectionExample.java

**Comment by jounghu** [comment]
@hxwabc 他这个map取值好像不支持数值和中划线，对当成减号和数值类型来处理

**Comment by killme2008** [comment]
如果key是数值，可以是 `#map.100`这样来访问，但是需要计算是不行，只能通过自定义函数。

对于 map 中的数组，可以通过 `#map.arrData)[0]`来访问，加个括号，但是你这里上面代码有一行写错了，应该是

```
map.put("arrData",arrData);
```
而不是放到 env里。
