### ISSUE TITLE
return type error

### ISSUE THREAD

**Issue by lixinlin** [killme2008/aviator#241]
Expression "1" got Long , it should be String

**Comment by lixinlin** [comment]
I know why

**Comment by killme2008** [comment]
没问题的，字符串相加就是 11，你传入的test是字符串。

**Comment by killme2008** [comment]
The expression `"1"` 's value is a long type， so there is no problem here, please read the document carefully.

If you want a string, the expression should be `"'1'"`, the string should be quoted by `"` or `'`'.

**Comment by lixinlin** [comment]
问题出在计算结果被程序反复迭代进去参与计算，结果执行到判断语句的时候永远不成立，因为两个类型不同

**Comment by lixinlin** [comment]
本以为是对变量值进行一次表达式求值出的问题，结果发现不是，现在搞不清楚问题到底出在哪里了，需要继续跟踪一下

**Comment by lixinlin** [comment]
你建议的给值为“‘1’”我试了也不行，比较的奇怪了

**Comment by lixinlin** [comment]
跑过去了，给的值是“1”，“‘1’”试了也可以过，用了类型强制转换

**Comment by killme2008** [comment]
你这个代码我看不懂，所以不知道什么是对，什么是错。你贴的代码编译都编译不了的。

**Comment by killme2008** [comment]
基本原则就那样：

1.   `1` 表示的就是数字
2.  `"1"` 或者 `'1'` 都是字符串，单引号，双引号都可以
3.  加法是重载的，对于字符串和其他任何对象相加都是拼接，数字之间才是算术运算。

仔细阅读文档吧。

**Comment by lixinlin** [comment]
没事了，那段代码是伪代码，不是真实代码，只是为了表示处理过程的，实际问题就是表达式求值出来是字符串，然后把结果设置为环境变量，后面再用那个比较语句的表达式比较变量值，发现从环境变量里面取到的是数值，不是字符串类型，导致比较结果不对，我跟踪了一下源代码，发现是那个编译的时候把"11"编译成了Long类型导致的，如果让他编译成字符串就要在内层再包裹一层单引号，而我的应用场景下，那个变量有可能是另外的表达式，不好再包一层，所以出现了这个问题，不好再包裹一层的情况下我就对结果进行类型转换，转换成字符串再去处理，结果就对了，呵呵，虽然有点别扭，但是这个也是没办法的事，话说回来，表达式引擎里面也确实不好处理这种情况，毕竟二次编译表达式的时候确确实实没有被包裹，从java语法的角度来说，那个字符串里面确实是数值，不是字符串，刚开始我以为是引擎出了问题，后来多次跟踪发现是二次编译的时候出的问题，所以问题就关闭了，本来打算撤销的，发现没有撤销功能，呵呵

**Comment by lixinlin** [comment]
话说回来那个missingfunction的机制还真是好用，以前改源码的方式用这种新的机制代码量缩减了非常多

**Comment by killme2008** [comment]
@lixinlin 好的，有问题再联系
