### ISSUE TITLE
如何增加自定义运算符

### ISSUE THREAD

**Issue by will86** [killme2008/aviator#244]
想请教个问题，我在使用av5.0的版本，想重写一些运算符的逻辑

通过如下方法，知道可以重新OperatorType中已经枚举的运算符，
`AviatorEvaluator.getInstance().addOpFunction(OperatorType.xx, new xxOperatorFunction());`

另外，我还想自定义一些OperatorType枚举项中不存在的其他运算符。
想知道调用什么方法能自定义运算符呢？

谢谢！

**Comment by killme2008** [comment]
这个不支持的，新增运算符是需要改parser的。
