### ISSUE TITLE
重写赋值(=)和判断相等(==)两个运算符不生效

### ISSUE THREAD

**Issue by will86** [killme2008/aviator#245]
我使用的5.0版本，现在已经通过一下方法重写了加减乘除运算符，
`AviatorEvaluator.getInstance().addOpFunction(OperatorType.xx, new xxOperatorFunction());`

现在想重写如下两个运算符

- EQ("==", 2)
- ASSIGNMENT("=", 2) / DEFINE("=", 2)

使用了和加减乘除运算符重写同样的方法，绑定了运算符和自定义的方法实现，但运行时却发现没有生效。
在=运算符 和 == 运算符的自定义方法实现中 `call` 方法的第一行断点都进不去。
我的代码如下

`

    public static void main(String[] args) {

        // 注册自定义运算符的实现
        AviatorEvaluator.getInstance().addOpFunction(OperatorType.ASSIGNMENT, new MyAssignmentOperator());

        // 编译表达式
        Expression exp = AviatorEvaluator.getInstance().compile("a = b");
        Map<String, Object> map = new HashMap<String, Object>();
        map.put("a", 1);
        map.put("b", 2);
        // 执行表达式语句
        Object ret = exp.execute(map);

        System.out.println(ret);
    }

    private static class MyAssignmentOperator extends AbstractFunction {
        private static final long serialVersionUID = 7576612041375445104L;

        @Override
        public AviatorObject call(Map<String, Object> env, AviatorObject arg1, AviatorObject arg2) {
            int result = arg1.compareEq(arg2, env);
            return AviatorBoolean.valueOf(result == 0);
        }

        @Override
        public String getName() {
            return OperatorType.ASSIGNMENT.getToken();
        }
    }
`

main方法中期望打印出Boolean类型执行结果，但现在打印的是2

想请教下，对=运算符或==运算符重写时，有其他需要额外注意的地方吗？多谢！

**Comment by killme2008** [comment]
`==` 我测试是可以的，赋值目前不支持

**Comment by killme2008** [comment]
`EQ` 的测试如下：
```java
 this.instance.addOpFunction(OperatorType.EQ, new AbstractFunction() {


      @Override
      public AviatorObject call(final Map<String, Object> env, final AviatorObject arg1,
          final AviatorObject arg2) {
        if (!arg1.getValue(env).equals(arg2.getValue(env))) {
          return AviatorBoolean.TRUE;
        }
        return AviatorBoolean.FALSE;
      }

      @Override
      public String getName() {
        return OperatorType.EQ.getToken();
      }
    });

    assertFalse((boolean) this.instance.execute("1==1"));
    assertTrue((boolean) this.instance.execute("0==1"));
    
```

**Comment by will86** [comment]
感谢作者回复。
我的本意是调换`==`和`=`两个运算符的含义，表达式是想提供给非技术人员使用，对他们不好接受`==`是判断是否正确的运算符，见名之意，`=`他们更认为是判断是否相等的运算符（sql和excel中判断两者相等也是使用`=`）而恰好他们一般不需要写脚本，所以`=`基本用不到在此场景下，想调换`==`和`=`的逻辑。
目前5.0版本下，这种运算符重载目前是不支持吗

**Comment by killme2008** [comment]
@will86 一直没有支持赋值的重载，刚提交了代码，在 5.0.1 会支持

**Comment by will86** [comment]
@killme2008  感谢作者，给力！

**Comment by killme2008** [comment]
发布了 5.0.1
