### ISSUE TITLE
表达式计算BigDecimal 如何指定精度和舍入方式？

### ISSUE THREAD

**Issue by blueskycheryl** [killme2008/aviator#247]
表达式计算BigDecimal 如何指定精度和舍入方式？

如：total_debt / total_asset * 100
decimal(total_debt / total_asset * 100).setScale(2, BigDecimal.ROUND_HALF_EVEN)

**Comment by killme2008** [comment]
MATH_CONTEXT 选项

https://www.yuque.com/boyan-avfmj/aviatorscript/yr1oau#MATH_CONTEXT

**Comment by killme2008** [comment]
通过 `AviatorEvaluatorInstance#setOption` 设置。
