### ISSUE TITLE
double handle bug 

### ISSUE THREAD

**Issue by yuzzjj** [killme2008/aviator#249]
version  last release 5.0.0
jvm 1.8
Map<String, Object> param = new HashMap<>();
		double dosage_frequency_double = 0.1428571;
		System.out.println(dosage_frequency_double < 0.1428571);
		AviatorEvaluatorInstance aviatorEvaluatorInstance = AviatorEvaluator.newInstance();
		String expr1 = "println(dosage_frequency_double < 0.1428571); dosage_frequency_double== 0.1428571";
		Expression expression2 = aviatorEvaluatorInstance.compile(expr1);
		param.put("dosage_frequency_double", dosage_frequency_double);
		System.out.println(expression2.execute(param));

<<<<<<<<<<<-result->>>>>>>>>>>>>
false       正确 [java]
true        错误 【aviator】
false       错误【aviator】

**Comment by yuzzjj** [comment]
看到另外一个 issue  应该强制使用 decimal(dosage_frequency_double)== decimal(0.1428571)

**Comment by killme2008** [comment]
浮点数本来就这样啊，浮点数的比较应该用减法，然后限制差值
