### ISSUE TITLE
=和==重载后表达式编译出错

### ISSUE THREAD

**Issue by will86** [killme2008/aviator#250]
作者你好，感谢5.0.1的发布，我能重写=和==两个运算符，并交换了两个运算符的逻辑功能。

我现在遇到的问题是，重写了=和==之后，简单表达式测试如1=3这样，=能当作原有==来处理，能返回false，达到我预期的效果。
但脚本中用到了==赋值后，编译错误了。

我的测试代码如下：

`
public class AVTest0606 {

    public static void main(String[] args) throws IOException {

        final boolean override = true;

        Map<String, Object> env = new HashMap<>();
        env.put("dataList", new ArrayList<>());
        // env.put("dataList", null);
        String expression = "";
        if (override) {
            expression += "let a == (dataList = nil);";
        }
        else {
            expression += "let a = (dataList == nil);";
        }
        expression += "p(a ? 'list is null' : ('list.length = ' + count(dataList)));";
        AviatorEvaluatorInstance instance = AviatorEvaluator.getInstance();

        // 重写==和=运算符
        if (override) {
            instance.addOpFunction(OperatorType.EQ, new MyEqOperator());
            instance.addOpFunction(OperatorType.ASSIGNMENT, new MyAssignmentOperator());
            instance.addOpFunction(OperatorType.DEFINE, new MyDefineOperator());
        }

        instance.execute(expression, env);
    }

    /**
     * 重写等号（==）运算符<br>
     *
     */
    public static class MyEqOperator extends AbstractFunction {

        /**
         * 
         */
        private static final long serialVersionUID = 6534110642481027497L;

        @Override
        public AviatorObject call(Map<String, Object> env, AviatorObject arg1, AviatorObject arg2) {
            ((Env) env).override((String) arg1.getValue(env), arg2.getValue(env));
            // env.put((String) arg1.getValue(env), arg2.getValue(env));
            return arg2;
        }

        @Override
        public String getName() {
            return OperatorType.EQ.getToken();
        }
    }

    /**
     * 重写等号（=）运算符<br>
     */
    public static class MyAssignmentOperator extends AbstractFunction {

        /**
         * 
         */
        private static final long serialVersionUID = 7576612041375445104L;

        @Override
        public AviatorObject call(Map<String, Object> env, AviatorObject arg1, AviatorObject arg2) {
            int result = arg1.compareEq(arg2, env);
            return AviatorBoolean.valueOf(result == 0);
        }

        @Override
        public String getName() {
            return OperatorType.ASSIGNMENT.getToken();
        }
    }

    /**
     * 重写等号（=）运算符<br>
     *
     */
    private static class MyDefineOperator extends AbstractFunction {

        /**
         * 
         */
        private static final long serialVersionUID = 1330158298329655398L;

        @Override
        public AviatorObject call(Map<String, Object> env, AviatorObject arg1, AviatorObject arg2) {
            int result = arg1.compareEq(arg2, env);
            return AviatorBoolean.valueOf(result == 0);
        }

        @Override
        public String getName() {
            return OperatorType.DEFINE.getToken();
        }
    }
}
`

以上main方法中，override 改为false，使用原有语义，则能正常使用；
override改为true后，使用重写后的运算符逻辑， 编译时报错。报错信息如下：

> Exception in thread "main" com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error: invalid token at 7, lineNumber: 1, token : [type='Char',lexeme='=',index=7],
while parsing expression: `
let a == (^^^
`
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1297)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1260)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1211)
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1387)
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1404)
	at AVTest0606.main(AVTest0606.java:40)

麻烦看下，这是我哪里逻辑有问题吗，谢谢！

**Comment by killme2008** [comment]
重载运算符，只是改变运算符的“副作用”，无法改变优先级和语法特性，比如这里 let 还是只能和 `=` 一起使用。
