### ISSUE TITLE
如果表达式从外部输入，如何防止恶意代码注入？

### ISSUE THREAD

**Issue by GuoYaxiang** [killme2008/aviator#251]
如果引擎计算的表达式是从外部输入的，如何检查代码中是否包含恶意的代码（如死循环等）？

如： `while true {}`

如何防止此类恶意代码的注入？
如何关闭引擎中对于循环（for、while）的支持？

**Comment by killme2008** [comment]
仔细看下文档 https://www.yuque.com/boyan-avfmj/aviatorscript/ou23gy#elOSu

**Comment by Drincann** [comment]
[Options.MAX_LOOP_COUNT](https://www.yuque.com/boyan-avfmj/aviatorscript/yr1oau#MnJ2T) 好像无法防止无限递归出现？

我们想控制脚本执行的超时时间，请问有什么好的姿势推荐吗？
