### ISSUE TITLE
自定义表达式中用或连接，高并发执行时偶尔失败(每天1000W+多调用，每周出现一次)

### ISSUE THREAD

**Issue by whdwsl** [killme2008/aviator#252]
表达式类似：seq.contains_key(a.extTags, 'property') || listEqualCheck(b.theSkus,'extTags.element', 2) || listEqualCheck(b.theSkus,'extTags.element', 3)
listEqualCheck是一个自定义方法，用来判断b.theSkus（是一个list）中每个对象中的extTags属性（是一个map）中key值为element对应的value是否为2.
相同的入参，两次执行结果不同，一直在复现中，没有找到必须的场景。但从日志上来看，返回结果异常时，相同的线程中只执行了listEqualCheck(b.theSkus,'extTags.element', 3)
l，没有执行listEqualCheck(b.theSkus,'extTags.element', 2)的日志 。
疑问1：用或连接，是不同的线程来执行吗？（还没看代码，但感觉上应该是一个线程执行整个表达式）
疑问2：能否提供点意见，我需要从哪个类打点日志能更快的打到原因

**Comment by killme2008** [comment]
1. aviator 是无状态的，唯一有状态的是你传入的 map，你需要自行保证这个 map 不会被并发修改， aviator 也不会启动线程，除非你的自定义函数启动了，默认就是执行在当前线程。

2. 建议看下执行过程中有没有涉及并发或者全局变量修改的东西。

**Comment by whdwsl** [comment]
map没有修改，且自定义方法中也是单线程的。从日志上看，listEqualCheck(b.theSkus,'extTags.element', 2) 没有打印这个入参的日志，所以怀疑这个没有执行。

**Comment by killme2008** [comment]
avaitor 支持短路运算的，如果 `||` 左边已经是 true 了，后面不会执行。

**Comment by whdwsl** [comment]
这个我知道的。表达式中共3项，第1项和第三项是false，第二项值为true，日志里只有第三项的日志 ，没有第二项的日志 ，返回结果是false，但真实的应该 返回true才对

**Comment by killme2008** [comment]
如果怀疑是 bug，请给出可复现的代码，这样的怀疑没有意义的。如果要跟踪执行，可以打开 TRACE_EVAL 选项。

**Comment by whdwsl** [comment]
是想请你帮忙看下怎么跟踪，TRACE_EVAL我先找下文档看下怎么开。

**Comment by killme2008** [comment]
https://www.yuque.com/boyan-avfmj/aviatorscript/yr1oau#TRACE_EVAL

**Comment by whdwsl** [comment]
TRACE_EVAL是用system.out输出的，没有线程名，我这里是多线程执行，不太好看。
[Aviator TRACE] Func : listEqualCheck(<JavaType, [Lcom.jd.purchase.domain.old.bean.SKU;@6844e854, SKU[]>,<String, extTags.isFlimPrint>,<Long, 2>)
[Aviator TRACE] Func : listEqualCheck(<JavaType, [Lcom.jd.purchase.domain.old.bean.SKU;@59fadfb4, SKU[]>,<String, extTags.isFlimPrint>,<Long, 2>)
[Aviator TRACE] <Boolean, false> || <Boolean, false> => <Boolean, false>
[Aviator TRACE] <Boolean, false> || <Boolean, false> => <Boolean, false>
[Aviator TRACE] Func : listEqualCheck(<JavaType, [Lcom.jd.purchase.domain.old.bean.SKU;@53d78f9a, SKU[]>,<String, extTags.isFlimPrint>,<Long, 3>)
[Aviator TRACE] Result : false
[Aviator TRACE] <Boolean, false> || <Boolean, false> => <Boolean, false>
[Aviator TRACE] Result : false
[Aviator TRACE] <Boolean, false> || <Boolean, false> => <Boolean, false>
[Aviator TRACE] Func : listEqualCheck(<JavaType, [Lcom.jd.purchase.domain.old.bean.SKU;@7e66f5b9, SKU[]>,<String, extTags.isFlimPrint>,<Long, 3>)
[Aviator TRACE] Func : listEqualCheck(<JavaType, [Lcom.jd.purchase.domain.old.bean.SKU;@59fadfb4, SKU[]>,<String, extTags.isFlimPrint>,<Long, 2>)
[Aviator TRACE] Func : listEqualCheck(<JavaType, [Lcom.jd.purchase.domain.old.bean.SKU;@27835db8, SKU[]>,<String, extTags.isFlimPrint>,<Long, 3>)

再请教下， 
[Aviator TRACE] <Boolean, false> || <Boolean, false> => <Boolean, false>
这一行是，单个方法返回的还是整个表达式返回的

**Comment by killme2008** [comment]
这个是其中一个步骤，从左到右执行，先求值条件，然后执行 `||`，你这里是两个 `||`，最后一个就是整个表达式的结果了。

**Comment by whdwsl** [comment]
表达式没变过，一直是三个条件，两个 || 符号， 这么看是不是少一个？

**Comment by killme2008** [comment]
这不是两次执行吗？

```
[Aviator TRACE] <Boolean, false> || <Boolean, false> => <Boolean, false>
[Aviator TRACE] Result : false
[Aviator TRACE] <Boolean, false> || <Boolean, false> => <Boolean, false>
```

**Comment by killme2008** [comment]
不用怀疑 aviator 的正确性，已经稳定运行了快10年的东西了，检查自己代码吧。 能重现你再打开这个 issue 。

**Comment by data-server** [comment]
`String scase = "result1 || result2";
        Map data = new HashMap();
        data.put("result1",true);
        Expression compiledExp = AviatorEvaluator.getInstance().compile(scase);
        Object result = compiledExp.execute(data);
        log.info("result:{}", result);`
result1 || result2  ====> result = true
result2 || result1  ====> throw exception
