### ISSUE TITLE
自动转换BigDecimal时成功，但是精度错误

### ISSUE THREAD

**Issue by baiyapeng** [killme2008/aviator#254]
```
AviatorEvaluatorInstance evaluatorInstance = AviatorEvaluator.getInstance();
//evaluatorInstance.setOption(Options.ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL, true);
Expression script = evaluatorInstance.compile("a*100", true);
/** 结果为<<BigDecimal>> **/
BigDecimal bd = (BigDecimal) script.execute(script.newEnv("a", new BigDecimal(34.13)));
/** 数值为<<3413.0000000000005>> **/
System.out.println(bd.doubleValue());
```
![image](https://user-images.githubusercontent.com/20579573/85215369-21235f80-b3aa-11ea-9929-1690ec14478f.png)

但是直接传入参数时，数值正确
```
AviatorEvaluatorInstance evaluatorInstance = AviatorEvaluator.getInstance();
evaluatorInstance.setOption(Options.ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL, true);
Expression script = evaluatorInstance.compile("34.13*100", true);
/** 结果为<<BigDecimal>> **/
BigDecimal bd = (BigDecimal) script.execute();
/** 数值为<<3413.0>> **/
System.out.println(bd.doubleValue());
```
![image](https://user-images.githubusercontent.com/20579573/85215404-b888b280-b3aa-11ea-9ea9-040d83136fec.png)

**Comment by killme2008** [comment]
你转成 double 了，理解下浮点数吧

**Comment by killme2008** [comment]
不过你这里是因为传入的 BigDecimal 是用 ` new BigDecimal(34.13)`，这种方式本来就是会有精度的问题，参见 javadoc

https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#BigDecimal-double-

如果是精确地要 `34.13` 这个数值，需要用字符串来构造 `new BigDecimal("34.13")`。

但是 `toDoubleValue` 仍然会有丢失精度的问题，如果要保证精度应该全程用 `BigDecimal`，展现用 `toPlainString()`，取小数位用 DecimalFormat 之类来转换。

浮点数的精度问题找一本书看看就了解了，或者 wikipedia https://en.wikipedia.org/wiki/IEEE_754

Decimal 的使用看看 https://juejin.im/post/5d81e96b51882507ba2269d8

**Comment by baiyapeng** [comment]
感谢
