### ISSUE TITLE
请问有对应的javascript解析校验开源工具吗？

### ISSUE THREAD

**Issue by dnxbjyj** [killme2008/aviator#255]
诉求：页面输入aviator表达式，希望在页面输入框输入时就能用js对表达式合法性进行校验。

那么请问有对应的js校验开源工具可以实现这个诉求吗？谢谢

**Comment by killme2008** [comment]
这个准备提供一个 check 方法，可以调用到后端来检测

**Comment by dnxbjyj** [comment]
这样也可以满足诉求，感谢
