### ISSUE TITLE
aviator可否支持设置变量前后缀，支持mybatis那样的语法？

### ISSUE THREAD

**Issue by myfreeway** [killme2008/aviator#26]
在使用时，发现有个语法上的小纠结。
比如我想用mybatis的map文件那样的语法。一堆字符串混合着#{变量名}，这种语法比较易用。
而且一看就知道哪个是变量。
但是aviator的语法是类似java那样的语法。需要写很多单引号拼接字符串。
aviator可否支持设置变量前后缀，支持mybatis那样的语法？
假如不支持的话，我想到的办法是，自己做一层转换。
按mybatis语法配置。把函数和变量名都写到#{}里。然后执行表达式前，把#{替换成'+，把}替换成+'。去掉头尾孤立的多余符号。

**Comment by killme2008** [comment]
抱歉，这个不准备支持，您可以做下变量名替换预处理。
