### ISSUE TITLE
WebSphere9中编译无反应

### ISSUE THREAD

**Issue by MacleZhou** [killme2008/aviator#260]
Hi, 我用的是4.2.10版本，在WebSphere9.0.0.7中系统编译如下表达式时没有反应，无任何log输出。啥原因？
amount-(thirdPartyPayments!=nil ? reduce(thirdPartyAmount, +, 0) : 0.00

我的代码如下：
//Open trace model
        AviatorEvaluator.setOption(Options.TRACE_EVAL, true);
        //统一将结果处理为BigDecimal类型
        AviatorEvaluator.setOption(Options.ALWAYS_PARSE_FLOATING_POINT_NUMBER_INTO_DECIMAL, true);
        log.debug("compileExpress["+calcBaseKey.getKey()+"]." + formula.getCode() + " compile begin： " + formula.getExpression());
        Expression expression  = AviatorEvaluator.compile(formula.getExpression());
        
formula.getExpression()就是：amount-(thirdPartyPayments!=nil ? reduce(thirdPartyAmount, +, 0) : 0.00

**Comment by killme2008** [comment]
编译希望什么反应？  TRACE_EVAL 是跟踪执行过程。

**Comment by MacleZhou** [comment]
抱歉，没说清楚。编译时一直没有返回，我后边的日志都不能输出。

**Comment by MacleZhou** [comment]
另外，发现我贴的表达式忘记了一个括号，amount-(thirdPartyPayments!=nil ? reduce(thirdPartyAmount, +, 0) : 0.00)

**Comment by killme2008** [comment]
在 sun jdk 没有问题，你这个可能是很老的一个 bug，建议增加环境变量 `-Daviator.preferClassloaderDefiner=true` 试试

**Comment by killme2008** [comment]
参考  https://github.com/killme2008/aviator/issues/228
