### ISSUE TITLE
map对象的整形通过FunctionUtils.getJavaObject() 方法后转换为了小数

### ISSUE THREAD

**Issue by RouGang** [killme2008/aviator#262]
public class MapCompValueFunction extends AbstractFunction {

  @Override
  public AviatorObject call(Map<String, Object> env,
                            AviatorObject arg1, AviatorObject arg2,
                            AviatorObject arg3) {
    String result = "";
    Map<String, Object> maps = (Map<String, Object>) FunctionUtils.getJavaObject(arg1, env);
    String str = FunctionUtils.getStringValue(arg2,env);
    String paramName = FunctionUtils.getStringValue(arg3,env);
    Map<String,Map<String,Object>>  map = (Map<String, Map<String,Object>>) maps.get(str);
    if (MapUtils.isNotEmpty(map)) {
      Map<String,Object>  questionMap = map.get("question");
      Map<String,Object> resultMap  = (Map<String,Object>)questionMap.get("value");
      if(MapUtils.isNotEmpty(resultMap)){
        result = MapStringUtils.toStr(resultMap.get(paramName));
      }
    }

    return new AviatorString(result);
  }

  @Override
  public String getName() {
    return "mapcompvalue";
  }
}

**Comment by killme2008** [comment]
这跟 aviator 没关系，你传入是什么样，那就是什么样。
