### ISSUE TITLE
aviator使用变量语法糖a.b时遇到的问题

### ISSUE THREAD

**Issue by MikcalJason** [killme2008/aviator#264]
使用的是aviator 5.0.1
现象：当我本项目中不引入commons-beanutils-core包时，默认使用的是commons-beanutils-core-1.8.0.jar.这个时候报错了
![image](https://user-images.githubusercontent.com/29418990/86987903-afc91680-c1c9-11ea-90ae-08b0b00d2736.png)
原因：可能是这个方法PropertyUtilsBean.addBeanIntrospector并没有使用到commons-beantils1.9.3，spring默认使用了commons-beanutils-core-1.8.0
![image](https://user-images.githubusercontent.com/29418990/86988264-70e79080-c1ca-11ea-86ea-e064cb25d395.png)

**Comment by MikcalJason** [comment]
望优化一下，外部的项目不用再引用commons-beanutils-core包

**Comment by killme2008** [comment]
这是包冲突了，自行解决即可。
