### ISSUE TITLE
AviatorEvaluator.compile 生成的Expression execute时是否支持可重入？

### ISSUE THREAD

**Issue by wangdxh** [killme2008/aviator#266]
同一个Expression对象 是否可以在多线程中同时进行execute，传入的map参数不一样

**Comment by killme2008** [comment]
你写的表达式只要是线程安全的，他就是线程安全的。

**Comment by wangdxh** [comment]
了解，表达式执行时 访问的对象都是在map里面的，每次执行数据context不同，而且如果不引入其他的函数，那就是线程安全的。

**Comment by yanghaogn** [comment]
> 你写的表达式只要是线程安全的，他就是线程安全的。

请问下，写的表达式是线程安全是什么意思？

如果我们用的是3.3.0，表达式类似"a == 1 && b >= c && d >= 10"，这种是线程安全的么？

AviatorEvaluator.execute(expressionStr, dataMap, true).asInstanceOf[Boolean]
