### ISSUE TITLE
安装脚本不能正常运行

### ISSUE THREAD

**Issue by EAFA0** [killme2008/aviator#269]
home 中提供的安装脚本不能正常运行
![image](https://user-images.githubusercontent.com/34804700/88248851-29d2c280-ccd5-11ea-94fd-73c91f9484d7.png)
删除 130,140,141 行中的 ` 之后正常运行了
![image](https://user-images.githubusercontent.com/34804700/88248895-4c64db80-ccd5-11ea-8305-2bdef7a4039f.png)

**Comment by EAFA0** [comment]
macOS 10.15.6
Bash 3.2.57

**Comment by EAFA0** [comment]
修改后的脚本

**Comment by killme2008** [comment]
被我改坏了，感谢反馈，我修下

**Comment by EAFA0** [comment]
> 被我改坏了，感谢反馈，我修下

&我好像多删了一点东西，140 和 141 行中间的 ` 不用删除是吧

**Comment by killme2008** [comment]
修复了
https://github.com/killme2008/aviator/commit/dfb642d90fb31f2659d33daf4402c453e94b6189
