### ISSUE TITLE
长时间运行性能会下降

### ISSUE THREAD

**Issue by greatestrabit** [killme2008/aviator#27]
我们现在在生产环境中使用发现，程序在运行较长时间之后，同样的公式，响应时间会变的越来越慢，下面贴出来我们使用的测试代码片段

[issue.zip](https://github.com/killme2008/aviator/files/1134676/issue.zip)

PS： GC方面未见明显异常

**Comment by killme2008** [comment]
从原理上来说不会有这样的问题，况且用在生产环境的很多了，没有听到过此类报告。

从你给的测试代码来看，问题是复杂化了，干扰因素更多（线程池、web容器等），简单地一个 Java Main 程序，重复运行一个表达式或者多个表达式 ，做对比就可以看出问题了。请提交一个更简单的可以复现的代码。

**Comment by killme2008** [comment]
没有后续报告，先关闭了。
