### ISSUE TITLE
导入实例方法，执行时报错问题

### ISSUE THREAD

**Issue by jackcailj** [killme2008/aviator#276]
定义如下类：

public class Math  {
    
    public  int calc(int x,int y){
        return x+y;
    }
}

使用addInstanceFunctions("math",Math.Class)导入

执行math.calc(1,2)，报错：Cannot cast java.lang.Long to com.jianghu.ext.function.Math

调试时发现
ClassMethodFunction类variadicCall方法，下面这断代码报异常
其中pTypes长度为3，第1个是Math类，第2个是int，第3个是int
jArgs长度为2：第1个是1，第2个是2
return FunctionUtils
            .wrapReturn(this.handle.invokeWithArguments(Reflector.boxArgs(this.pTypes, jArgs)));

**Comment by killme2008** [comment]
注意看文档，实例方法的调用应该是 `calc(math, 1, 2)`

**Comment by killme2008** [comment]
实例方法的调用都需要从 `instance.method(args)` 变成 `method(instance, args)`

**Comment by jackcailj** [comment]
好的，谢谢，文档没看仔细
