### ISSUE TITLE
请问aviator能否支持jdk8的lamba表达式

### ISSUE THREAD

**Issue by laozhuang727** [killme2008/aviator#28]
因为项目中用到了大量的jdk8语法，请问aviator能否支持jdk8的lamba表达式？

非常感谢

**Comment by killme2008** [comment]
抱歉，如果支持函数的话，那就不是一个简单的表达式引擎，而可能发展成一门微型语言了，这不是 aviator 的定位，你可以使用 groovy / javascript 等 ScriptEngine 引擎。
