### ISSUE TITLE
能否支持自定义添加新的运算？或者可以重写某个运算的实现逻辑？

### ISSUE THREAD

**Issue by cwh056133** [killme2008/aviator#280]
（1）能否支持自定义添加新的运算？
 目前需要用到一些自定义运算时，是去修改源码（大概要改动8-9个类），添加对应的运算符号、运算逻辑，改动起来稍稍有些麻烦。所以想问问，能否提供相关的接口（或其他方式），能让用户动态添加一些运算。
（2）能否重写某个运算的实现逻辑？
因业务需求，可能某个运算不太符合当前的业务，所以能否有个渠道可以让用户来覆写原运算的逻辑。

PS：看了源码，这一块使用枚举+ switch 来编写，不是通过对象封装的方式（每种运算抽象成对象），改动的话会比较大 。希望作者可以考虑一下我提的这些建议，也希望aviator越来越强大。

感谢.

**Comment by killme2008** [comment]
1. 不准备支持这类需求，你可以将自定义运算符写成自定义函数来使用 https://www.yuque.com/boyan-avfmj/aviatorscript/xbdgg2
2. 使用运算符重载  https://www.yuque.com/boyan-avfmj/aviatorscript/ydllav#5hq4k
