### ISSUE TITLE
AviatorBoolean 不支持 bitXor 、bitOr、bitAnd

### ISSUE THREAD

**Issue by senowang** [killme2008/aviator#281]
AviatorBoolean 不支持 bitXor 、bitOr、bitAnd 运算符，在一些场景中 使用`||` 和 `&&` 由于短路的作用，会导致后面的表达式不执行，而业务中需要执行后面的表达式，去做一定的逻辑。需要支持 位运算

**Comment by killme2008** [comment]
如果需要副作用，建议将表达式改写下，用 let 语句将两边的条件赋予变量，然后对变量进行逻辑运算。

**Comment by killme2008** [comment]
类似原来是 `exp1 || exp2` 的，修改为 `let a = exp1 ; let b = exp2; a || b`

**Comment by senowang** [comment]
这种方式是可以，但是用起来有点别扭，我还是改写下源码实现。

**Comment by killme2008** [comment]
无需改写代码，可以重载运算符，支持下 boolean 即可。https://www.yuque.com/boyan-avfmj/aviatorscript/ydllav#5hq4k

**Comment by senowang** [comment]
谢谢。这种方式挺好用
