### ISSUE TITLE
数字科学计数法等于判断问题

### ISSUE THREAD

**Issue by chengxuetao** [killme2008/aviator#282]
boolean result1 = (Boolean) AviatorEvaluator.execute("1.8620639E7==18620639");
boolean result2 = (Boolean) AviatorEvaluator.execute("1.9455127E7==19455127");
result1 是 true result2 是 false

**Comment by killme2008** [comment]
浮点数的比较要考虑精度，无法简单地用等于，不等于，一般是比较差值是否小于某个绝对值
