### ISSUE TITLE
是否可以将表达式分类处理，以专门优化提高性能

### ISSUE THREAD

**Issue by lijiajun1979** [killme2008/aviator#286]
如果将表达式分成，只能数值计算，支持比较操作符的计算，支持脚本的计算几种分类，是否能针对每种分类做更多优化。
这样比如如果设置只用到比较操作符的数值计算，是否能获得更好性能。现在做1千万次支持比较操作符的计算要执行2秒多，能不能更接近原生的执行速度

**Comment by killme2008** [comment]
你的 2000 万次比较是编译模式还是非编译模式？ 1 秒 1000 万次我觉的足以满足绝大多数应用的性能。瓶颈在于类型判断和包装上。

**Comment by killme2008** [comment]
如果你确定你的数据类型都是数字，可以重载比较运算符，去掉类型判断，直接默认为是数字来比较。

关于重载可以参考 https://www.yuque.com/boyan-avfmj/aviatorscript/ydllav#5hq4k

**Comment by lijiajun1979** [comment]
我的机器i5 3代,做计算是BigDecimal的简单数值计算，大概速度是1000万次用2秒多，我有需求是想提供指标表达式，然后多个指标表达式之间提供比较和与或非的操作，最后获得一个bool返回值。多个指标表达式可以做自定义方法，返回字符串或者bigdecimal。这么做是想实现规则检查，这样就可以将规则完全写成表达式的形式。

**Comment by lijiajun1979** [comment]
做了java8的sriptengine使用groovy的嵌入表达式的测试，编译模式，最简单的一个乘法一个加法的表达式，执行10万次，要3秒左右，非常慢，现在看计算上只有你这个项目和Fel性能比较高，不过fel不更新了也不支持bool计算。这个项目还能把性能一个数量级么？1亿次或者5000万次

**Comment by lijiajun1979** [comment]
发现个东西叫janino，同样的计算，1亿次2.7秒，可以快10倍

**Comment by killme2008** [comment]
@lijiajun1979 因为他就是一个 java 的动态编译器，如果追求跟原生一样的效率，我建议用它吧。 aviator 的定位并不是这个。理论上说 #99 这个 feature 可以做到，不过暂时优先级不高。
