### ISSUE TITLE
Double类型，<有bug

### ISSUE THREAD

**Issue by Sinmes** [killme2008/aviator#3]
`package com.zork.streaming

import java.util

import com.googlecode.aviator.{AviatorEvaluator, Expression}

/**
  * Created by sinmes on 16/9/21.
  */
object Test {
  var expressList:scala.collection.mutable.MutableList[util.HashMap[String, AnyRef]] = _

  def getresult(env: util.HashMap[String, AnyRef]): scala.collection.mutable.MutableList[util.HashMap[String, AnyRef]] = {

    val list = new scala.collection.mutable.MutableList[util.HashMap[String, AnyRef]]
    for (temp <- expressList){
      if ("true".equals(temp.get("expression").asInstanceOf[Expression].execute(env).toString)) {
        val maptmp = new util.HashMap[String, AnyRef]()
        maptmp.put("event", env.toString)
        maptmp.put("info", temp.toString)
        list += maptmp
      }
    }
    list
  }

  def compileExpression (expressionsstr : String) {
    expressList = new scala.collection.mutable.MutableList[util.HashMap[String, AnyRef]]
    val exstrArray = expressionsstr.split(":")
    for (str <- exstrArray) {
      var map = new util.HashMap[String, AnyRef]()
      map.put("expression", AviatorEvaluator.compile(str))
      map.put("alarminfo", str)
      expressList += map
    }
  }

  def main(args: Array[String]): Unit = {
    val a = Test
    a.compileExpression("idea_exe_CpuUsage<1110")
    val c = new util.HashMap[String, AnyRef]()
    c.put("idea_exe_CpuUsage111", "17.00000".toDouble.asInstanceOf[AnyRef])
    c.put("timestamp","1474423160")
    c.put("IP", "10.176.3.6")
    c.put("hostname", "hl")
    c.put("SystemType", "WindowsComputer")
    val d = a.getresult(c)
    d.foreach(e => {
      val itr = e.entrySet().iterator()
      while (itr.hasNext){
        val tmp  = itr.next()
        println(tmp.getKey+":"+tmp.getValue)
      }
    })
  }
}
`

输出结果是：
event:{timestamp=1474423160, idea_exe_CpuUsage111=17.0, IP=10.176.3.6, hostname=hl, SystemType=WindowsComputer}
info:{expression=Script_1474599424448_0@606145c5, alarminfo=idea_exe_CpuUsage<1110}

**Comment by killme2008** [comment]
没 get 到 point？ 什么问题？

17.0 就是 double 了。

**Comment by killme2008** [comment]
你表达式是 `idea_exe_CpuUsage<1110`

填充的变量却是 `idea_exe_CpuUsage111`。

我先关闭了，如果确认有问题再打开吧。

**Comment by Sinmes** [comment]
@killme2008 
表达式是 idea_exe_CpuUsage<1110

填充的变量却是 idea_exe_CpuUsage111
正式因为 表达式key是idea_exe_CpuUsage，变量map里 没有这个key，  使用< 还是会输出。 正确的结果不应该是不输出吗?

**Comment by killme2008** [comment]
你可能没有仔细阅读文档，任何情况下 nil 都比其他元素小

https://github.com/killme2008/aviator/wiki#nil-%E5%AF%B9%E8%B1%A1
