### ISSUE TITLE
集合访问问题

### ISSUE THREAD

**Issue by adealjason** [killme2008/aviator#30]
举个例子：
public class Order{
     private List<SubOrder> subOrders;
}
public class SubOrder{
    private String subOrderId;
}
如果表达式是:order. subOrders可以拿到一个List对象
但是我如果要想获取subOrderId时，表达式如：order.subOrders.subOrderId
这个Aviator无法解析，因为Aviator认为subOrderId是List的属性，
请问，如果想实现上述的问题，Aviator是否支持，表达式该如何描述？
谢谢

**Comment by killme2008** [comment]
你应该是希望遍历整个列表，然后取出所有的 subOrderId,　返回一个集合。遍历可以用 seq.map，理想的状态是
`seq.map(order.subOrders, fn(order) -> order.subOrderId)`,，第二个参数是一个匿名函数。可惜 aviator　不支持匿名函数，所以你需要实现一个自定义函数来获取　order　的 subOrderId，然后使用 seq.map　调用这个函数  `seq.map(order.subOrders, 你的自定义函数名)`

关于自定义函数参考

https://github.com/killme2008/aviator/wiki#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%87%BD%E6%95%B0
