### ISSUE TITLE
在使用时如果不将表达式编译结果缓存会不会造成持续的内存增长

### ISSUE THREAD

**Issue by simonHome** [killme2008/aviator#34]
1.执行速度快和编译速度优先有什么区别。
2.如果在执行不传入true的第二个参数，每次都进行编译一次会不会造成内存的持续增长。

**Comment by killme2008** [comment]
1. 顾名思义，执行速度快就是表达式变化多，无法缓存编译结果的，编译速度优先，适合表达式变化不多，需要长时间运行的。
2. 要开启 class unloading

**Comment by killme2008** [comment]
在 3.2.0 版本后，这个问题已经得到彻底解决

https://github.com/killme2008/aviator/releases/tag/aviator-3.2.0

**Comment by simonHome** [comment]
感谢
