### ISSUE TITLE
根据表达式判断是否存在某个自定义函数

### ISSUE THREAD

**Issue by onlyZohar** [killme2008/aviator#36]
`AviatorEvaluator.compile("SUM(5, 6)");`
如上面的表达式,编译后可以判断是否存在某个自定义函数吗？

**Comment by killme2008** [comment]
可以调用 ` AviatorFunction .getFunction(String name)` 来判断。

**Comment by onlyZohar** [comment]
可以您理解错了，我的意思是说有没有一个方法可以判断我的表达式是否调用了某个自定义函数,
如:`SUM(5, 6)`表达式,调用了SUM()这个自定义函数;'SUM(5, MAX(1,2,3))'表达式，调用了SUM(),MAX()这两个自定义函数

**Comment by killme2008** [comment]
理论上可以结合编译后的 `Expression#getVariableFullNames()` 加上　`AviatorFunction .getFunction(String name)` 来判断。
