### ISSUE TITLE
是否能够自定义操作符，例如两个矩阵的加和减

### ISSUE THREAD

**Issue by yelangchs** [killme2008/aviator#37]
我的需求是 类似这样
Matrix a = new Matrix()
Matrix b = new Matrix()

能否重载+ 来计算 a + b

**Comment by killme2008** [comment]
不支持，你可能需要实现一个 matric 库，类似 matric.add(x,y) 之类的操作，参见

https://github.com/killme2008/aviator/wiki#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%87%BD%E6%95%B0
