### ISSUE TITLE
有打算支持运算符重载吗

### ISSUE THREAD

**Issue by onlyZohar** [killme2008/aviator#40]
目前在用这个表达式引擎来实现一些excel函数,"&"这个运算符在excel里面是表示内容拼接,我是通过改源码的方式来实现的,如果可以提供运算符重载就很方便了

**Comment by killme2008** [comment]
这个想法有过，将运算符也作为自定义函数提供，理论上可以搞的。

**Comment by killme2008** [comment]
3.3.0 开始支持重载运算符，参考文档

https://github.com/killme2008/aviator/wiki#%E9%87%8D%E8%BD%BD%E8%BF%90%E7%AE%97%E7%AC%A6

预计明天同步到maven
