### ISSUE TITLE
trace 表达式的中间计算结果

### ISSUE THREAD

**Issue by killme2008** [killme2008/aviator#41]
类似 aa && bb && cc 这样的逻辑表达式，当返回 false 的时候，可能想知道哪个步骤终止了

**Comment by Victor-Gun** [comment]
怎么使用这个特性呢

**Comment by Victor-Gun** [comment]
只能打印到控制台么

**Comment by killme2008** [comment]
@Victor-Gun 设置 `Options.TRACE_EVAL` 就可以开启，如果要打印到地方，请设置 `AviatorEvaluator.setTraceOutputStream` 指向其他输出流，比如某个文件的 FileOutputStream

不过这个选项会极大的影响性能，不要在生产环境开。

**Comment by Victor-Gun** [comment]
@killme2008 感谢回答，不过还有个疑问，
项目中现在要实现这样一个功能
execute("(aa && bb) || (cc && dd)")
需要知道哪个规则项执行失败使得整个表达式返回false
这个能实现么
