### ISSUE TITLE
支持 if/else

### ISSUE THREAD

**Issue by killme2008** [killme2008/aviator#42]

**Comment by xiagaohui** [comment]
是要准备支持if/else了吗

**Comment by zhangzhenhua92** [comment]
赞

**Comment by hug3id** [comment]
如果支持if-else，顺便把return也支持下呀~

**Comment by killme2008** [comment]
@hug3id 嗯，准备周末有空写下，升级成 AviatorScript

**Comment by tinyblink** [comment]
@killme2008 催更啦，期待功能早日可用

**Comment by AJ-Liang** [comment]
学习了，Script好啊，可以满足很多需求

**Comment by AJ-Liang** [comment]
@killme2008 最近在做服务编排上的调研，如果aviator可以支持script，那在编排上的依赖会相当轻了，期待更新

**Comment by killme2008** [comment]
完成了一个原型，放假后会抓紧搞下

**Comment by tinyblink** [comment]
@killme2008 赞。
aviator和groovy之类的脚本引擎比优势是什么？应用场景有什么差别？

**Comment by AJ-Liang** [comment]
@tinyblink 
groovy 比较重，aviator相对轻很多了，不过aviator目前没有脚本支持，不太好做更多的逻辑定义，所以很期待这个版本的更新

**Comment by tinyblink** [comment]
@tinyblink 重是指资源占用还是使用方式？

**Comment by killme2008** [comment]
已在 5.0 版本支持，包括循环语句、作用域、局部变量等

https://www.yuque.com/boyan-avfmj/aviatorscript/mcoghv
https://github.com/killme2008/aviator/releases/tag/aviator-5.0.0-beta1
