### ISSUE TITLE
获取集合中的对象属性异常

### ISSUE THREAD

**Issue by kainhong** [killme2008/aviator#46]
final Map<String, Object> env = new HashMap<String, Object>();
		List<Dto> ary = new ArrayList<>();
		ary.add(new Dto());
		env.put("lst", ary);		
		AviatorEvaluator.execute("#lst[0].name", env);
------------------
com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error:illegal expression at 12, current token: [type='Number',lexeme='.',index=11]

**Comment by Alingww** [comment]
闲来无聊，测评一下这个表达式引擎，发现同样的问题，这个是一个bug,居然直接访问list中复杂对象的属性是不行的，如果底层用的是commons-beanutils实现的是支持的，我测试过，代码如下：Object indexedProperty = PropertyUtils.getNestedProperty(users, "[0].age");System.out.println(indexedProperty);结果成功输出 第一个元素中年龄age的属性值。所以，大神这个bug是可以修复的,赶紧修复一下吧。哈哈

**Comment by Alingww** [comment]
Map<String, Object> env = new HashMap<String, Object>();
env.put("users", users);
Object execute3 = AviatorEvaluator.execute("#users.[0].name",env);底层嵌套取值，我想着大神一定用的这个方法来实现的：PropertyUtils.getNestedProperty(),于是我将表达式写成"users.[0].name" 尝试一下，可以取到值，哈哈，大神对于Map,List中复杂对象取值一定没有仔细研究过， 只怪我太聪明，大神这个bug,也可以不用修复了，主要是更新一下文档，强调说明，这两个坑踩的人比较多。

**Comment by killme2008** [comment]
感谢提醒

**Comment by killme2008** [comment]
此问题已经修复，并且请使用 `#users.[0].name`访问即可。
