### ISSUE TITLE
转义字符使用问题

### ISSUE THREAD

**Issue by onlyZohar** [killme2008/aviator#49]
需要返回:"你好',
这是我的表达式:AviatorEvaluator.execute("'\"你好\''")，运行是报错的,请问如果需要返回多个特殊的字符应该怎么写

**Comment by killme2008** [comment]
你好，这是个 bug，理论上说可以写成:

```java
 String s = (String)AviatorEvaluator.execute("'\"你好\\''");
```

我会在本周末修复下，谢谢．

**Comment by killme2008** [comment]
转义已经支持，4.0.0-RC正式发布
https://github.com/killme2008/aviator/releases/tag/aviator-4.0.0-RC
