### ISSUE TITLE
禁用语法糖功能

### ISSUE THREAD

**Issue by hustfly** [killme2008/aviator#50]
能否增加一个禁用语法糖的配置选项。比如说在编译表达式替换变量时，变量字符串如果本来就包括'.', '*'这样的关键字时，又不合适去掉的时候，就按照语法糖解析了。

**Comment by Alingww** [comment]
诸如.[] > < = 等特殊字符，处理支持变量中转义就OK了。

**Comment by ylquan** [comment]
有什么计划支持这个功能么

**Comment by killme2008** [comment]
转义在master代码里已经支持，预计这周发布 3.0

**Comment by killme2008** [comment]
4.0.0-RC发布，新增选项 `ENABLE_PROPERTY_SYNTAX_SUGAR`，默认 true，可关闭

https://github.com/killme2008/aviator/releases/tag/aviator-4.0.0-RC
