### ISSUE TITLE
在使用调试模式文件输出时候无法输出文件

### ISSUE THREAD

**Issue by madull** [killme2008/aviator#51]
try {
            AviatorEvaluator.setTraceOutputStream(new FileOutputStream(new File("aviator.log")));
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        AviatorEvaluator.setOption(Options.TRACE_EVAL, true);

AviatorEvaluator.execute

然后我发现文件中没有相应的数据,我看了下代码
OperationRuntime.java
 public static void printTrace(String msg) {
    System.out.println("[Aviator TRACE] " + msg);
  }
是否应该替换outputString 而不是System.out.println("[Aviator TRACE] " + msg);

**Comment by killme2008** [comment]
setTraceOutputStream　原来是用于跟踪字节码的，跟　TRACE_EVAL　没有关系，这个 API 将被移除．

**Comment by iamwx** [comment]
这个功能为什么要移除啊，我想看生成的字节码应该怎么看？
