### ISSUE TITLE
访问list集合中对象的属性抛异常

### ISSUE THREAD

**Issue by Alingww** [killme2008/aviator#52]
Map<String, Object> env = new HashMap<String, Object>();
	env.put("users", users);
        Object execute3 = AviatorEvaluator.execute("users[0].name",env);其中 users 是list对象。
如果底层用的是commons-beanutils实现的是支持的，我测试过，代码如下：Object indexedProperty = PropertyUtils.getNestedProperty(users, "[0].age");System.out.println(indexedProperty);结果成功输出 第一个元素中年龄age的属性值。所以，大神这个bug是可以修复的,赶紧修复一下吧。哈哈

**Comment by Alingww** [comment]
Map<String, Object> env = new HashMap<String, Object>();
env.put("users", users);
Object execute3 = AviatorEvaluator.execute("#users.[0].name",env);底层嵌套取值，我想着大神一定用的这个方法来实现的：PropertyUtils.getNestedProperty(),于是我将表达式写成"users.[0].name" 尝试一下，可以取到值，哈哈，只怪我太聪明，大神这个bug,也不用修复了，更新一下文档吧。哈哈

**Comment by killme2008** [comment]
请参考上面回答，抱歉，我对 commons-beanutils不熟悉。
