### ISSUE TITLE
List集合注入env，量大了会不会内存泄露？

### ISSUE THREAD

**Issue by aalansehaiyang** [killme2008/aviator#57]
public class LoanRuleAviatorTest {

    private  List<String> list = Arrays.asList("上海","北京","杭州");

    @Test
    public void jieyun_validate() {
        AviatorEvaluator.addFunction(new AddFunction());

        Map<String, Object> validateData = new HashMap<String, Object>();
        validateData.put("age", 30);
        validateData.put("car", "不");
        validateData.put("house", "");
        validateData.put("insurance", "没有");
        validateData.put("city","杭州");
        validateData.put("list",list);

        List<Expression> expressList = new ArrayList<>();
        expressList.add(AviatorEvaluator.compile("age>=22 && age<=50"));
        expressList.add(AviatorEvaluator.compile("(car == '有')|| (house == '有')|| (insurance == '有') "));
        expressList.add(AviatorEvaluator.compile("include(list,city)"));

        for (Expression e : expressList) {
            Boolean result = (Boolean) e.execute(validateData);
            System.out.println(e.toString() + "返回结果：" + result); // false
        }

    }

=========
 private  List<String> list = Arrays.asList("上海","北京","杭州");

这一行代码作为全局变量放在外面，每次request请求，都要放到validateData里，会不会影响validateData对象回收？如果并发量高了，会不会导致OOM？

**Comment by killme2008** [comment]
这跟 OOM 没有关系，况且放多次，也只是引用。
