### ISSUE TITLE
变量不存在时候 能否当nil处理

### ISSUE THREAD

**Issue by ylquan** [killme2008/aviator#59]
变量a 不存在是 执行 a==nil 返回ture
如果是a.b 不存在 执行 a.b==nil 抛出异常 感觉两种情况下的行为不一致
第二种应该也是nil

**Comment by killme2008** [comment]
可以的，这是个合理的需求。

**Comment by killme2008** [comment]
已发布 4.0.0-RC，新增选项 `NIL_WHEN_PROPERTY_NOT_FOUND`

https://github.com/killme2008/aviator/releases/tag/aviator-4.0.0-RC
