### ISSUE TITLE
循环调用AviatorEvaluator.execute的时候会出现问题

### ISSUE THREAD

**Issue by Allen0769** [killme2008/aviator#63]
循环调用AviatorEvaluator.execute的时候，我发现java的非堆内存会慢慢的增长，随着时间的推移，那段循环的代码被执行次数越多，非堆内存最终会因为只有增加没有释放而爆了

**Comment by killme2008** [comment]
默认是非 cache 模式，每次调用 execute 都会动态生成一个新类，这种情况下会耗费 perm 或者 metaspace 空间，具体见

https://stackoverflow.com/questions/24074164/what-is-the-use-of-metaspace-in-java-8

如果表达式规模有限，都建议启用 cache 模式，除了 class 内存占用之外还可以提升性能

```java
public static Object execute(String expression, Map<String, Object> env, boolean cached)
```

还可以通过预编译来优化和缓存

https://github.com/killme2008/aviator/wiki#%E7%BC%96%E8%AF%91%E8%A1%A8%E8%BE%BE%E5%BC%8F

**Comment by killme2008** [comment]
另外就是尽量使用 JDK 1.7 及以上版本， aviator 也尽量使用 3.2.0 以上版本

https://github.com/killme2008/aviator/releases/tag/aviator-3.2.0

**Comment by anguslee** [comment]
最新版本代码在非cache模式下仍然会有这个内存问题吗？

**Comment by anguslee** [comment]
最新版本默认是cache模式还是非cache模式？
