### ISSUE TITLE
Question - Expression compiled to bytecode and java upgrade

### ISSUE THREAD

**Issue by Melozzola** [killme2008/aviator#64]
Hi, if I understood well Aviator compiles expressions to byte code and evaluates them on the fly. My question is what happens if I store the bytecode to avoid recompiling and then I upgrade the java version at a later stage. Will the compiled expression potentially break?

Thank you.

**Comment by killme2008** [comment]
The compiled java bytecode version is 1.6.0 and can be changed by API

```
AviatorEvaluator.setBYTECODE_VER( Opcodes.V1_7);
```

So you can control it by yourself.
