### ISSUE TITLE
 Method code too large

### ISSUE THREAD

**Issue by AYWWWWW** [killme2008/aviator#66]
hello，我在使用aviator的时候，发现有一个表达式长度的限制。
MethodWriter
`if (code.length > 65536) {
        throw new RuntimeException("Method code too large!");
      }`
请问这个是基于什么样的考虑呢？

**Comment by killme2008** [comment]
hello，这应该是 JVM 的限制，反应到这里就是 asm 的限制，单个 method 的最大大小是 64K．
参见
https://stackoverflow.com/questions/24256316/method-code-too-large-in-groovy-grails

如果有这么大的表达式，建议适当拆分，多次求值．

**Comment by AYWWWWW** [comment]
收到，多谢
