### ISSUE TITLE
FuntionUtils的getStringValue不希望直接抛NPE

### ISSUE THREAD

**Issue by resurgencedna** [killme2008/aviator#67]
FuntionUtils的getStringValue方法中，当value为null时，会直接抛出空指针异常
而在我们的业务场景中是不适用的，因为直接抛空指针会导致整个表达式执行失败，我们倾向于直接返回null，是否抛异常由自定义的扩展函数自己去处理，我认为这样更合理

**Comment by killme2008** [comment]
恩，这个代码我也忘了当时为什么这么选择了，　应该改下．

**Comment by killme2008** [comment]
已在 4.1.0 修复
