### ISSUE TITLE
aviator与BeanShell的差异在哪里呢？

### ISSUE THREAD

**Issue by cnzzr** [killme2008/aviator#7]
本项目与 BeanShell的区别在于？ 轻量吗？

**Comment by killme2008** [comment]
@cnzzr beanshell 我印象中是一门完整的语言，aviator 不是，只是专注于表达式计算，除了更小巧之外，过去的测试表明性能也比 beanshell 好很多，最新的对比测试没有做了。有兴趣可以自行对比下。
