### ISSUE TITLE
自定义函数返回AviatorRuntimeJavaType对象，表达式中如何获取函数返回对象属性值

### ISSUE THREAD

**Issue by mrfsong** [killme2008/aviator#71]
getBaseSiteInfoById(obj.siteId).getOrgId() ？ 
getBaseSiteInfoById(obj.siteId).orgId？
这两种方式都报错

**Comment by killme2008** [comment]
这样的语法确实不支持，因为目前这种 dot 语法只是 beanutils 的包装，而这里是一个链式调用，后续会尝试支持下。
目前你只能再封装一个方法来获取另一个属性。

**Comment by srcCodeExplorer** [comment]
请问这个功能目前支持了不

**Comment by luckyqiao** [comment]
同问，现在支持链式调用了吗
