### ISSUE TITLE
自定义函数传递的参数不能是json的字符串吗？

### ISSUE THREAD

**Issue by lizhitao0923** [killme2008/aviator#72]

**Comment by killme2008** [comment]
可以的，请描述具体问题

**Comment by BigBlackSheep** [comment]
在使用 spring中 使用Aviator自定义函数中 似乎是反射调用? 我想在自定义函数中查找redis数据 ,但是redisService是个null.在定义函数中没有注入进来.请问需要怎么解决?
public AviatorObject variadicCall(Map<String, Object> env, AviatorObject... args) {

    String blackListCode = (String) env.get("blackListCode");
    boolean exis = redisService.exists(blackListCode);



bigzhan@126.com
 
发件人： dennis zhuang
发送时间： 2018-07-27 15:43
收件人： killme2008/aviator
抄送： Subscribed
主题： Re: [killme2008/aviator] 自定义函数传递的参数不能是json的字符串吗？ (#72)
可以的，请描述具体问题

**Comment by lizhitao0923** [comment]
谢谢，可以了。原来是需要加单引号和每个字段需要转义
AviatorEvaluator.exec("xxFunction('{\"xxField\":[{\"id\":1417,\"name\":\"邢台\"}]}', 398, '0,2,5,100,1417', 0, 100, 'false', 1, 2)")
