### ISSUE TITLE
三元表达式bug

### ISSUE THREAD

**Issue by clayclayclay** [killme2008/aviator#73]
以下为测试代码：
        String exp = "(a > 1 ? 1.16 : 2)";
        Map<String, Object> env = Maps.newHashMap();
        env.put("a" ,2);
        AviatorResult<String> result1 = AviatorUtil.executeExpression(exp, env, String.class);
        assertEquals(1.16, result1.getValue());

测试结果：
java.lang.AssertionError: 
Expected :1.16
Actual   :1.1600000000000001

也就是说result.getValue()=1.1600000000000001
为什么不是1.16呢？

**Comment by killme2008** [comment]
浮点数精度问题，在 aviator 中所有浮点数都是 double。
https://zh.wikipedia.org/wiki/%E6%B5%AE%E7%82%B9%E6%95%B0

**Comment by clayclayclay** [comment]
@killme2008  还是不太理解，你能帮我简单解释一下这个三元表达式的执行过程吗？为什么我设定获取的result为String类型，但是最后却变成了double?

**Comment by killme2008** [comment]
@clayclayclay  AviatorUtil 并不是 aviator 提供的，请自行查看你们的项目代码。

**Comment by clayclayclay** [comment]
@killme2008  sorry，不好意思，没有留意到。我再补一个：
        String exp = "a > 1 ? 1.16 : 2";
        Map<String, Object> env = Maps.newHashMap();
        env.put("a" ,2);
        Expression expCompiled = AviatorEvaluator.compile(exp);
        Object obj = expCompiled.execute(env);
        assertEquals(1.16, obj);

最终obj的结果还是1.1600000000000001
我理解你之前是说，“在 aviator 中所有浮点数都是 double”，所以1.16会变成1.1600000000000001，但是如果我就是想获得1.16这个数值呢？
