### ISSUE TITLE
4.00rc版，正则表达式的分组结果不会放进env中

### ISSUE THREAD

**Issue by linlay** [killme2008/aviator#74]
希望通过某种形式，实现3.3版本的正则表达式放入env中。
虽然，我觉得表达式不改变env这个新设定没毛病。

**Comment by killme2008** [comment]
4.0.1 将正式支持赋值，彻底解决这个问题。

**Comment by xiagaohui** [comment]
4.00rc版本新建了一个env，为什么不用传进来的env，我们需要把函数的计算过程通过传入的env透出去

**Comment by killme2008** [comment]
4.0.0-RC 为了支持 lambda 闭包，引入了嵌套 env 的概念;
 4.1.0 新增了选项 `USE_USER_ENV_AS_TOP_ENV_DIRECTLY`，默认是 true，也就是兼容老版本的行为， top 级别的 env 将直接使用用户传入的 map。
