### ISSUE TITLE
Questions around licenses

### ISSUE THREAD

**Issue by Melozzola** [killme2008/aviator#76]
The licenses.txt states that the licence is LGPL Version 3, and in the code, the header is stating "either version 2.1 of the License, or (at your option) any later version".
The first question is: Is this library under LGPL Version 3 or 2.1?

Anyway, as you might know LGPL (especially v3) is problematic for corporates.
What I wanted to ask is if the choice of the license something you wanted and if it would be possible to switch to Apache 2.
If you upgrade to Apache 2, your library will benefit from it because it will be easier to adopt it and you will probably get more contributions too...

Thank you.

**Comment by killme2008** [comment]
1. It's LGPL v3.
2. I will consider it, thanks.
