### ISSUE TITLE
Hi, 编译问题

### ISSUE THREAD

**Issue by mylxy** [killme2008/aviator#8]
String str = "a==3+3";
这个编译为什么能通过呢？感觉不是正常的逻辑啊！计算的时候才报错，我觉得是不是编译的时候就不能通过吧

**Comment by killme2008** [comment]
这是个合法表达式啊，比较a 和 6 是否相等。

**Comment by mylxy** [comment]
是这样的吗？那为什么计算报错了，优先级不是这样吗？例(a==3)+3

**Comment by mylxy** [comment]
==这个优先级最低是吗？

**Comment by killme2008** [comment]
是的，逻辑运算符都是低于算术运算符的，不确定的就加括号。

这个编译不会报错的，如果不传入 a，那么默认返回 false，因为 nil 除了自身，不和其他任何东西相等。

https://github.com/killme2008/aviator/wiki#nil-%E5%AF%B9%E8%B1%A1
