### ISSUE TITLE
重载之后运算符优先级丢失问题

### ISSUE THREAD

**Issue by JQSoftCN** [killme2008/aviator#81]
//重载运算符
        AviatorEvaluator.addOpFunction(OperatorType.BIT_XOR, new AbstractFunction() {
            @Override
            public String getName() {
                return OperatorType.BIT_XOR.token;
            }

            @Override
            public AviatorObject call(Map<String, Object> env, AviatorObject num, AviatorObject cubic) {
                Object n = num.getValue(env);
                Object c = cubic.getValue(env);
                if (n instanceof Number && c instanceof Number) {
                    double ns = ((Number) n).doubleValue();
                    double cs = ((Number) c).doubleValue();
                    return new AviatorDouble(Math.pow(ns, cs));
                } else {
                    //非正常情况下，直接返回0
                    return new AviatorDouble(0);
                }
            }
        });

        String f="1+2+(3^2)";
        System.out.println(AviatorEvaluator.execute(f));

**Comment by JQSoftCN** [comment]
必须采用括号才能保证优先级，得到正确结果是12。
反之如下：
        String f="1+2+3^2";
        System.out.println(AviatorEvaluator.execute(f));  //得到结果是36

**Comment by killme2008** [comment]
确认不是 bug，  ^ 的优先级就是比较低的，参见 java 运算符优先级


https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html

**Comment by JQSoftCN** [comment]
哦，虽不合常规思路，但有Java标准可依，那就按标准走吧。谢谢回复。
