### ISSUE TITLE
关于自定义方法参数个数的疑问

### ISSUE THREAD

**Issue by coderstory** [killme2008/aviator#82]
自定义方法需要继承AbstractFunction，类提供了不同参数的重载
但没有提供可变参数的重载，也就是不确定参数个数的情况。
这个时候，只能使用seq filter map之类的方法么？

**Comment by killme2008** [comment]
针对可变参数自定义函数可继承 `AbstractVariadicFunction` 类，实现其中的 ` variadicCall(Map<String, Object> env, AviatorObject... args);` 方法即可。
