### ISSUE TITLE
StringSubStringFunction subString 方法建议替换成apache,StringUtils.substring那种

### ISSUE THREAD

**Issue by XiaoMaoGuai** [killme2008/aviator#86]
我在使用过程中，因为有个单位地址很长，我们只需要前20位，但是我不知道具体的长度，使用jdk，自带的
substring，如果长度不满足会报错,  因此 建议 StringSubStringFunction 里面的字符串截取采用apache,StringUtils.substring那种

**Comment by killme2008** [comment]
这个建议自己实现自定义函数，覆盖系统库的，目前的行为不适合修改了，担心会有兼容问题。
