### ISSUE TITLE
Aviator Spring boot  jsr94规范实现

### ISSUE THREAD

**Issue by mengxiangrui007** [killme2008/aviator#90]
Aviator Spring boot支持 实现
  https://github.com/mengxiangrui007/spring-boot-rule-jsr94

**Comment by killme2008** [comment]
:+1: 
你可以提个 MR 加个链接到 aviator 的 README 里面。

**Comment by mengxiangrui007** [comment]
谢谢  可以review下我的代码

**Comment by killme2008** [comment]
thanks
