### ISSUE TITLE
多个线程同时调用 AviatorEvaluator.execute() 会存在多线程安全问题吗

### ISSUE THREAD

**Issue by haoyuanqiang** [killme2008/aviator#91]
现在有一个需求，需要多线程并发执行计算任务，每个任务都会调用 AviatorEvaluator.execute() 进行表达式计算，如果不做任何措施，会存在线程安全问题吗？

**Comment by killme2008** [comment]
AviatorEvaluator.execute() 本身是线程安全的。只要你的表达式执行逻辑是线程安全的，传入的 env 是线程安全的，那就没有问题。

**Comment by haoyuanqiang** [comment]
好的，谢谢，这样我就可以放心的在项目中使用了

**Comment by zhangzhenhua92** [comment]
请问大神，env为确保线程安全的话，是否需要传入ConcurrentHashMap？

**Comment by killme2008** [comment]
核心的问题是你的 env 是否会被并发修改，跟传不传没关系。如果没有，那就不用　ConcurrentHashMap
