### ISSUE TITLE
表达式处理转义符\\时有问题

### ISSUE THREAD

**Issue by linlay** [killme2008/aviator#92]
AviatorEvaluator.execute(“‘\\’”, scope); // 会有问题
AviatorEvaluator.execute(“‘\\ ’”, scope); // 多一个空格就不会有问题 输出 \空格
AviatorEvaluator.execute(“‘\\,’”, scope); // 随便多个什么都不会有问题 输出 \,
AviatorEvaluator.execute(“‘\\\\’”, scope); // 依然有问题

**Comment by killme2008** [comment]
已在 4.1.0 中修复，正确的写法是需要四个斜杠 `'\\\\'`
